version: "0.2-SNAPSHOT"

grobidHome: ../grobid-home

corpusPath: resources/dataset/
tmpPath: tmp/

# path to Pub2TEI stylesheet repository as available at https://github.com/kermitt2/Pub2TEI under Stylesheets or to your custom one
stylesheetsPath: "Stylesheets"

# Limit the maximum number of requests, 0 means use the number of threads of the machine running the JVM
maxParallelRequests: 0

# CORS configuration for the web API service
corsAllowedOrigins: "*"
corsAllowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"
corsAllowedHeaders: "X-Requested-With,Content-Type,Accept,Origin"

server:
  type: custom
  idleTimeout: 120 seconds
  applicationConnectors:
    - type: http
      port: 8060
  adminConnectors:
    - type: http
      port: 8061
  registerDefaultExceptionMappers: false
  maxThreads: 2048
  maxQueuedRequests: 2048
  acceptQueueSize: 2048
  #requestLog:
  #    appenders: []

logging:
  level: INFO
  loggers:
    org.apache.pdfbox.pdmodel.font.PDSimpleFont: "OFF"
    org.glassfish.jersey.internal: "OFF"
    com.squarespace.jersey2.guice.JerseyGuiceUtils: "OFF"
  appenders:
    - type: console
      threshold: INFO
      timeZone: UTC
      # uncomment to have the logs in json format
      #layout:
      #  type: json
    - type: file
      currentLogFilename: logs/pub2tei-service.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/pub2tei-service-%d.log
      archivedFileCount: 5
      timeZone: UTC
      # uncomment to have the logs in json format
      #layout:
      #  type: json