<!-- ###########################################################################
#
#   File name: img.inc
#   Project: Journals
#   Description: LaTeX control sequence entities for inclusion in Journals DTDs
#	This should not contain anything which is also in one of the ISO files
#
#
#   External documents:
#
#
#   Author: Peter Haworth/A J Cox
#   Date created: 15/03/00
#
#   $Id$
#
#   Copyright (C) IOP Publishing Ltd 1999-2008
#   Portions Copyright International Organization for Standardization 1986
############################################################################ -->

<!ENTITY % iso_include SYSTEM "iso.inc">
%iso_include;

<!ENTITY percent	"&#x0025;">	<!-- percent sign -->
<!ENTITY endash		"&#x2013;">	<!-- en dash -->
<!ENTITY emdash		"&#x2014;">	<!-- em dash -->
<!ENTITY equal		" = ">		<!-- equal sign -->
<!ENTITY underscore	"_">		<!-- underscore -->
<!ENTITY lslash		"&#x0142;">	<!-- l slash -->
<!ENTITY Lslash		"&#x0141;">	<!-- L slash -->
<!ENTITY pounds		"&#x00A3;">	<!-- pound sign -->
<!ENTITY registered	"&#x00AE;">	<!-- registered trademark -->
<!ENTITY TM		"&#x2122;">	<!-- trademark -->
<!ENTITY trademark	"&#x2122;">	<!-- trademark -->


<!ENTITY calA		"&#x1D49C;">	<!-- Script A -->
<!ENTITY calB		 "&#x212C;">	<!-- Script B -->
<!ENTITY calC		"&#x1D49E;">	<!-- Script C -->
<!ENTITY calD		"&#x1D49F;">	<!-- Script D -->
<!ENTITY calE		 "&#x2130;">	<!-- Script E -->
<!ENTITY calF		 "&#x2131;">	<!-- Script F -->
<!ENTITY calG		"&#x1D4A2;">	<!-- Script G -->
<!ENTITY calH		 "&#x210B;">	<!-- Script H -->
<!ENTITY calI		 "&#x2110;">	<!-- Script I -->
<!ENTITY calJ		"&#x1D4A5;">	<!-- Script J -->
<!ENTITY calK		"&#x1D4A6;">	<!-- Script K -->
<!ENTITY calL		 "&#x2112;">	<!-- Script L -->
<!ENTITY calM		 "&#x2133;">	<!-- Script M -->
<!ENTITY calN		"&#x1D4A9;">	<!-- Script N -->
<!ENTITY calO		"&#x1D4AA;">	<!-- Script O -->
<!ENTITY calP		"&#x1D4AB;">	<!-- Script P -->
<!ENTITY calQ		"&#x1D4AC;">	<!-- Script Q -->
<!ENTITY calR		 "&#x211B;">	<!-- Script R -->
<!ENTITY calS		"&#x1D4AE;">	<!-- Script S -->
<!ENTITY calT		"&#x1D4AF;">	<!-- Script T -->
<!ENTITY calU		"&#x1D4B0;">	<!-- Script U -->
<!ENTITY calV		"&#x1D4B1;">	<!-- Script V -->
<!ENTITY calW		"&#x1D4B2;">	<!-- Script W -->
<!ENTITY calX		"&#x1D4B3;">	<!-- Script X -->
<!ENTITY calY		"&#x1D4B4;">	<!-- Script Y -->
<!ENTITY calZ		"&#x1D4B5;">	<!-- Script Z -->
<!ENTITY BbbA		"&#x1D538;">	<!-- Blackboard bold A -->
<!ENTITY BbbB		"&#x1D539;">	<!-- Blackboard bold B -->
<!ENTITY BbbC		 "&#x2102;">	<!-- Blackboard bold C -->
<!ENTITY BbbD		"&#x1D53B;">	<!-- Blackboard bold D -->
<!ENTITY BbbE		"&#x1D53C;">	<!-- Blackboard bold E -->
<!ENTITY BbbF		"&#x1D53D;">	<!-- Blackboard bold F -->
<!ENTITY BbbG		"&#x1D53E;">	<!-- Blackboard bold G -->
<!ENTITY BbbH		 "&#x210D;">	<!-- Blackboard bold H -->
<!ENTITY BbbI		"&#x1D540;">	<!-- Blackboard bold I -->
<!ENTITY BbbJ		"&#x1D541;">	<!-- Blackboard bold J -->
<!ENTITY BbbK		"&#x1D542;">	<!-- Blackboard bold K -->
<!ENTITY BbbL		"&#x1D543;">	<!-- Blackboard bold L -->
<!ENTITY BbbM		"&#x1D544;">	<!-- Blackboard bold M -->
<!ENTITY BbbN		 "&#x2115;">	<!-- Blackboard bold N -->
<!ENTITY BbbO		"&#x1D546;">	<!-- Blackboard bold O -->
<!ENTITY BbbP		 "&#x2119;">	<!-- Blackboard bold P -->
<!ENTITY BbbQ		 "&#x211A;">	<!-- Blackboard bold Q -->
<!ENTITY BbbR		 "&#x211D;">	<!-- Blackboard bold R -->
<!ENTITY BbbS		"&#x1D54A;">	<!-- Blackboard bold S -->
<!ENTITY BbbT		"&#x1D54B;">	<!-- Blackboard bold T -->
<!ENTITY BbbU		"&#x1D54C;">	<!-- Blackboard bold U -->
<!ENTITY BbbV		"&#x1D54D;">	<!-- Blackboard bold V -->
<!ENTITY BbbW		"&#x1D54E;">	<!-- Blackboard bold W -->
<!ENTITY BbbX		"&#x1D54F;">	<!-- Blackboard bold X -->
<!ENTITY BbbY		"&#x1D550;">	<!-- Blackboard bold Y -->
<!ENTITY BbbZ		 "&#x2124;">	<!-- Blackboard bold Z -->
<!ENTITY Bbbk		"&#x1D55C;">	<!-- Blackboard bold k -->
<!ENTITY frakA		"&#x1D504;">	<!-- Fraktur A -->
<!ENTITY frakB		"&#x1D505;">	<!-- Fraktur B -->
<!ENTITY frakC		 "&#x212D;">	<!-- Fraktur C -->
<!ENTITY frakD		"&#x1D507;">	<!-- Fraktur D -->
<!ENTITY frakE		"&#x1D508;">	<!-- Fraktur E -->
<!ENTITY frakF		"&#x1D509;">	<!-- Fraktur F -->
<!ENTITY frakG		"&#x1D50A;">	<!-- Fraktur G -->
<!ENTITY frakH		 "&#x210C;">	<!-- Fraktur H -->
<!ENTITY frakI		 "&#x2111;">	<!-- Fraktur I -->
<!ENTITY frakJ		"&#x1D50D;">	<!-- Fraktur J -->
<!ENTITY frakK		"&#x1D50E;">	<!-- Fraktur K -->
<!ENTITY frakL		"&#x1D50F;">	<!-- Fraktur L -->
<!ENTITY frakM		"&#x1D510;">	<!-- Fraktur M -->
<!ENTITY frakN		"&#x1D511;">	<!-- Fraktur N -->
<!ENTITY frakO		"&#x1D512;">	<!-- Fraktur O -->
<!ENTITY frakP		"&#x1D513;">	<!-- Fraktur P -->
<!ENTITY frakQ		"&#x1D514;">	<!-- Fraktur Q -->
<!ENTITY frakR		 "&#x211C;">	<!-- Fraktur R -->
<!ENTITY frakS		"&#x1D516;">	<!-- Fraktur S -->
<!ENTITY frakT		"&#x1D517;">	<!-- Fraktur T -->
<!ENTITY frakU		"&#x1D518;">	<!-- Fraktur U -->
<!ENTITY frakV		"&#x1D519;">	<!-- Fraktur V -->
<!ENTITY frakW		"&#x1D51A;">	<!-- Fraktur W -->
<!ENTITY frakX		"&#x1D51B;">	<!-- Fraktur X -->
<!ENTITY frakY		"&#x1D51C;">	<!-- Fraktur Y -->
<!ENTITY frakZ		 "&#x2128;">	<!-- Fraktur Z -->
<!ENTITY fraka		"&#x1D51E;">	<!-- Fraktur a -->
<!ENTITY frakb		"&#x1D51F;">	<!-- Fraktur b -->
<!ENTITY frakc		"&#x1D520;">	<!-- Fraktur c -->
<!ENTITY frakd		"&#x1D521;">	<!-- Fraktur d -->
<!ENTITY frake		"&#x1D522;">	<!-- Fraktur e -->
<!ENTITY frakf		"&#x1D523;">	<!-- Fraktur f -->
<!ENTITY frakg		"&#x1D524;">	<!-- Fraktur g -->
<!ENTITY frakh		"&#x1D525;">	<!-- Fraktur h -->
<!ENTITY fraki		"&#x1D526;">	<!-- Fraktur i -->
<!ENTITY frakj		"&#x1D527;">	<!-- Fraktur j -->
<!ENTITY frakk		"&#x1D528;">	<!-- Fraktur k -->
<!ENTITY frakl		"&#x1D529;">	<!-- Fraktur l -->
<!ENTITY frakm		"&#x1D52A;">	<!-- Fraktur m -->
<!ENTITY frakn		"&#x1D52B;">	<!-- Fraktur n -->
<!ENTITY frako		"&#x1D52C;">	<!-- Fraktur o -->
<!ENTITY frakp		"&#x1D52D;">	<!-- Fraktur p -->
<!ENTITY frakq		"&#x1D52E;">	<!-- Fraktur q -->
<!ENTITY frakr		"&#x1D52F;">	<!-- Fraktur r -->
<!ENTITY fraks		"&#x1D530;">	<!-- Fraktur s -->
<!ENTITY frakt		"&#x1D531;">	<!-- Fraktur t -->
<!ENTITY fraku		"&#x1D532;">	<!-- Fraktur u -->
<!ENTITY frakv		"&#x1D533;">	<!-- Fraktur v -->
<!ENTITY frakw		"&#x1D534;">	<!-- Fraktur w -->
<!ENTITY frakx		"&#x1D535;">	<!-- Fraktur x -->
<!ENTITY fraky		"&#x1D536;">	<!-- Fraktur y -->
<!ENTITY frakz		"&#x1D537;">	<!-- Fraktur z -->

<!-- Grave accent on italic letters -->
<!ENTITY graveA		"&#x1D434;&#x0300;">	<!-- italic A grave -->
<!ENTITY graveE		"&#x1D438;&#x0300;">	<!-- italic E grave -->
<!ENTITY graveI		"&#x1D43C;&#x0300;">	<!-- italic I grave -->
<!ENTITY graveO		"&#x1D442;&#x0300;">	<!-- italic O grave -->
<!ENTITY graveU		"&#x1D448;&#x0300;">	<!-- italic U grave -->
<!ENTITY gravea		"&#x1D44E;&#x0300;">	<!-- italic a grave -->
<!ENTITY gravee		"&#x1D452;&#x0300;">	<!-- italic e grave -->
<!ENTITY gravei		"&#x1D456;&#x0300;">	<!-- italic i grave -->
<!ENTITY graveo		"&#x1D45C;&#x0300;">	<!-- italic o grave -->
<!ENTITY graveu		"&#x1D462;&#x0300;">	<!-- italic u grave -->

<!-- Acute accent on italic letters -->
<!ENTITY acuteA		"&#x1D434;&#x0301;">	<!-- italic A acute -->
<!ENTITY acuteE		"&#x1D438;&#x0301;">	<!-- italic E acute -->
<!ENTITY acuteI		"&#x1D43C;&#x0301;">	<!-- italic I acute -->
<!ENTITY acuteO		"&#x1D442;&#x0301;">	<!-- italic O acute -->
<!ENTITY acuteU		"&#x1D448;&#x0301;">	<!-- italic U acute -->
<!ENTITY acuteY		"&#x1D44C;&#x0301;">	<!-- italic Y acute -->
<!ENTITY acutea		"&#x1D44E;&#x0301;">	<!-- italic a acute -->
<!ENTITY acutee		"&#x1D452;&#x0301;">	<!-- italic e acute -->
<!ENTITY acutei		"&#x1D456;&#x0301;">	<!-- italic i acute -->
<!ENTITY acuteo		"&#x1D45C;&#x0301;">	<!-- italic o acute -->
<!ENTITY acuteu		"&#x1D462;&#x0301;">	<!-- italic u acute -->
<!ENTITY acutey		"&#x1D466;&#x0301;">	<!-- italic y acute -->

<!-- Cedilla on upright letters -->
<!ENTITY Acedil		"A&#x0327;">	<!-- A cedilla -->
<!ENTITY Bcedil		"B&#x0327;">	<!-- B cedilla -->
<!ENTITY Dcedil		 "&#x1E10;">	<!-- D cedilla -->
<!ENTITY Ecedil		 "&#x0228;">	<!-- E cedilla -->
<!ENTITY Fcedil		"F&#x0327;">	<!-- F cedilla -->
<!ENTITY Hcedil		 "&#x1E28;">	<!-- H cedilla -->
<!ENTITY Icedil		"I&#x0327;">	<!-- I cedilla -->
<!ENTITY Jcedil		"J&#x0327;">	<!-- J cedilla -->
<!ENTITY Mcedil		"M&#x0327;">	<!-- M cedilla -->
<!ENTITY Ocedil		"O&#x0327;">	<!-- O cedilla -->
<!ENTITY Pcedil		"P&#x0327;">	<!-- P cedilla -->
<!ENTITY Qcedil		"Q&#x0327;">	<!-- Q cedilla -->
<!ENTITY Ucedil		"U&#x0327;">	<!-- U cedilla -->
<!ENTITY Vcedil		"V&#x0327;">	<!-- V cedilla -->
<!ENTITY Wcedil		"W&#x0327;">	<!-- W cedilla -->
<!ENTITY Xcedil		"X&#x0327;">	<!-- X cedilla -->
<!ENTITY Ycedil		"Y&#x0327;">	<!-- Y cedilla -->
<!ENTITY Zcedil		"Z&#x0327;">	<!-- Z cedilla -->
<!ENTITY acedil		"a&#x0327;">	<!-- a cedilla -->
<!ENTITY bcedil		"b&#x0327;">	<!-- b cedilla -->
<!ENTITY dcedil		 "&#x1E11;">	<!-- d cedilla -->
<!ENTITY ecedil		 "&#x0229;">	<!-- e cedilla -->
<!ENTITY fcedil		"f&#x0327;">	<!-- f cedilla -->
<!ENTITY gcedil		"g&#x0327;">	<!-- g cedilla -->
<!ENTITY hcedil		 "&#x1E29;">	<!-- h cedilla -->
<!ENTITY icedil		"i&#x0327;">	<!-- i cedilla -->
<!ENTITY jcedil		"j&#x0327;">	<!-- j cedilla -->
<!ENTITY mcedil		"m&#x0327;">	<!-- m cedilla -->
<!ENTITY ocedil		"o&#x0327;">	<!-- o cedilla -->
<!ENTITY pcedil		"p&#x0327;">	<!-- p cedilla -->
<!ENTITY qcedil		"q&#x0327;">	<!-- q cedilla -->
<!ENTITY ucedil		"u&#x0327;">	<!-- u cedilla -->
<!ENTITY vcedil		"v&#x0327;">	<!-- v cedilla -->
<!ENTITY wcedil		"w&#x0327;">	<!-- w cedilla -->
<!ENTITY xcedil		"x&#x0327;">	<!-- x cedilla -->
<!ENTITY ycedil		"y&#x0327;">	<!-- y cedilla -->
<!ENTITY zcedil		"z&#x0327;">	<!-- z cedilla -->

<!-- hacek or check accent over character -->
<!ENTITY Acheck		 "&#x01CD;">	<!-- check A -->
<!ENTITY Bcheck		"B&#x030C;">	<!-- check B -->
<!ENTITY Ccheck		 "&#x010C;">	<!-- check C -->
<!ENTITY Dcheck		 "&#x010E;">	<!-- check D -->
<!ENTITY Echeck		 "&#x011A;">	<!-- check E -->
<!ENTITY Fcheck		"F&#x030C;">	<!-- check F -->
<!ENTITY Gcheck		 "&#x01E6;">	<!-- check G -->
<!ENTITY Hcheck		 "&#x021E;">	<!-- check H -->
<!ENTITY Icheck		 "&#x01CF;">	<!-- check I -->
<!ENTITY Jcheck		"J&#x030C;">	<!-- check J -->
<!ENTITY Kcheck		 "&#x01E8;">	<!-- check K -->
<!ENTITY Lcheck		 "&#x013D;">	<!-- check L -->
<!ENTITY Mcheck		"M&#x030C;">	<!-- check M -->
<!ENTITY Ncheck		 "&#x0147;">	<!-- check N -->
<!ENTITY Ocheck		 "&#x01D1;">	<!-- check O -->
<!ENTITY Pcheck		"P&#x030C;">	<!-- check P -->
<!ENTITY Qcheck		"Q&#x030C;">	<!-- check Q -->
<!ENTITY Rcheck		 "&#x0158;">	<!-- check R -->
<!ENTITY Scheck		 "&#x0160;">	<!-- check S -->
<!ENTITY Tcheck		 "&#x0164;">	<!-- check T -->
<!ENTITY Ucheck		 "&#x01D3;">	<!-- check U -->
<!ENTITY Vcheck		"V&#x030C;">	<!-- check V -->
<!ENTITY Wcheck		"W&#x030C;">	<!-- check W -->
<!ENTITY Xcheck		"X&#x030C;">	<!-- check X -->
<!ENTITY Ycheck		"Y&#x030C;">	<!-- check Y -->
<!ENTITY Zcheck		 "&#x017D;">	<!-- check Z -->
<!ENTITY acheck		 "&#x01CE;">	<!-- check a -->
<!ENTITY bcheck		"b&#x030C;">	<!-- check b -->
<!ENTITY ccheck		 "&#x010D;">	<!-- check c -->
<!ENTITY dcheck		 "&#x010F;">	<!-- check d -->
<!ENTITY echeck		 "&#x011B;">	<!-- check e -->
<!ENTITY fcheck		"f&#x030C;">	<!-- check f -->
<!ENTITY gcheck		 "&#x01E7;">	<!-- check g -->
<!ENTITY hcheck		 "&#x021F;">	<!-- check h -->
<!ENTITY icheck		 "&#x01D0;">	<!-- check i -->
<!ENTITY jcheck		 "&#x01F0;">	<!-- check j -->
<!ENTITY kcheck		 "&#x01E9;">	<!-- check k -->
<!ENTITY lcheck		 "&#x013E;">	<!-- check l -->
<!ENTITY mcheck		"m&#x030C;">	<!-- check m -->
<!ENTITY ncheck		 "&#x0148;">	<!-- check n -->
<!ENTITY ocheck		 "&#x01D2;">	<!-- check o -->
<!ENTITY pcheck		"p&#x030C;">	<!-- check p -->
<!ENTITY qcheck		"q&#x030C;">	<!-- check q -->
<!ENTITY rcheck		 "&#x0159;">	<!-- check r -->
<!ENTITY scheck		 "&#x0161;">	<!-- check s -->
<!ENTITY tcheck		 "&#x0165;">	<!-- check t -->
<!ENTITY ucheck		 "&#x01D4;">	<!-- check u -->
<!ENTITY vcheck		"v&#x030C;">	<!-- check v -->
<!ENTITY wcheck		"w&#x030C;">	<!-- check w -->
<!ENTITY xcheck		"x&#x030C;">	<!-- check x -->
<!ENTITY ycheck		"y&#x030C;">	<!-- check y -->
<!ENTITY zcheck		 "&#x017E;">	<!-- check z -->

<!-- breve accent over character -->
<!ENTITY Bbreve		"B&#x0306;">	<!-- breve B -->
<!ENTITY Cbreve		"C&#x0306;">	<!-- breve C -->
<!ENTITY Dbreve		"D&#x0306;">	<!-- breve D -->
<!ENTITY Ebreve		 "&#x0114;">	<!-- breve E -->
<!ENTITY Fbreve		"F&#x0306;">	<!-- breve F -->
<!ENTITY Hbreve		"H&#x0306;">	<!-- breve H -->
<!ENTITY Ibreve		 "&#x012C;">	<!-- breve I -->
<!ENTITY Jbreve		"J&#x0306;">	<!-- breve J -->
<!ENTITY Kbreve		"K&#x0306;">	<!-- breve K -->
<!ENTITY Lbreve		"L&#x0306;">	<!-- breve L -->
<!ENTITY Mbreve		"M&#x0306;">	<!-- breve M -->
<!ENTITY Nbreve		"N&#x0306;">	<!-- breve N -->
<!ENTITY Obreve		 "&#x014E;">	<!-- breve O -->
<!ENTITY Pbreve		"P&#x0306;">	<!-- breve P -->
<!ENTITY Qbreve		"Q&#x0306;">	<!-- breve Q -->
<!ENTITY Rbreve		"R&#x0306;">	<!-- breve R -->
<!ENTITY Sbreve		"S&#x0306;">	<!-- breve S -->
<!ENTITY Tbreve		"T&#x0306;">	<!-- breve T -->
<!ENTITY Vbreve		"V&#x0306;">	<!-- breve V -->
<!ENTITY Wbreve		"W&#x0306;">	<!-- breve W -->
<!ENTITY Xbreve		"X&#x0306;">	<!-- breve X -->
<!ENTITY Ybreve		"Y&#x0306;">	<!-- breve Y -->
<!ENTITY Zbreve		"Z&#x0306;">	<!-- breve Z -->
<!ENTITY bbreve		"b&#x0306;">	<!-- breve b -->
<!ENTITY cbreve		"c&#x0306;">	<!-- breve c -->
<!ENTITY dbreve		"d&#x0306;">	<!-- breve d -->
<!ENTITY ebreve		 "&#x0115;">	<!-- breve e -->
<!ENTITY fbreve		"f&#x0306;">	<!-- breve f -->
<!ENTITY hbreve		"h&#x0306;">	<!-- breve h -->
<!ENTITY ibreve		 "&#x012D;">	<!-- breve i -->
<!ENTITY jbreve		"j&#x0306;">	<!-- breve j -->
<!ENTITY kbreve		"k&#x0306;">	<!-- breve k -->
<!ENTITY lbreve		"l&#x0306;">	<!-- breve l -->
<!ENTITY mbreve		"m&#x0306;">	<!-- breve m -->
<!ENTITY nbreve		"n&#x0306;">	<!-- breve n -->
<!ENTITY obreve		 "&#x014F;">	<!-- breve o -->
<!ENTITY pbreve		"p&#x0306;">	<!-- breve p -->
<!ENTITY qbreve		"q&#x0306;">	<!-- breve q -->
<!ENTITY rbreve		"r&#x0306;">	<!-- breve r -->
<!ENTITY sbreve		"s&#x0306;">	<!-- breve s -->
<!ENTITY tbreve		"t&#x0306;">	<!-- breve t -->
<!ENTITY vbreve		"v&#x0306;">	<!-- breve v -->
<!ENTITY wbreve		"w&#x0306;">	<!-- breve w -->
<!ENTITY xbreve		"x&#x0306;">	<!-- breve x -->
<!ENTITY ybreve		"y&#x0306;">	<!-- breve y -->
<!ENTITY zbreve		"z&#x0306;">	<!-- breve z -->

<!-- barred characters (in maths) -->
<!-- XXX The images for these are italic -->
<!ENTITY barA		 "&#x0100;">	<!-- bar A -->
<!ENTITY barB		"B&#x0304;">	<!-- bar B -->
<!ENTITY barC		"C&#x0304;">	<!-- bar C -->
<!ENTITY barD		"D&#x0304;">	<!-- bar D -->
<!ENTITY barE		 "&#x0112;">	<!-- bar E -->
<!ENTITY barF		"F&#x0304;">	<!-- bar F -->
<!ENTITY barG		 "&#x1E20;">	<!-- bar G -->
<!ENTITY barH		"H&#x0304;">	<!-- bar H -->
<!ENTITY barI		 "&#x012A;">	<!-- bar I -->
<!ENTITY barJ		"J&#x0304;">	<!-- bar J -->
<!ENTITY barK		"K&#x0304;">	<!-- bar K -->
<!ENTITY barL		"L&#x0304;">	<!-- bar L -->
<!ENTITY barM		"M&#x0304;">	<!-- bar M -->
<!ENTITY barN		"N&#x0304;">	<!-- bar N -->
<!ENTITY barO		 "&#x014C;">	<!-- bar O -->
<!ENTITY barP		"P&#x0304;">	<!-- bar P -->
<!ENTITY barQ		"Q&#x0304;">	<!-- bar Q -->
<!ENTITY barR		"R&#x0304;">	<!-- bar R -->
<!ENTITY barS		"S&#x0304;">	<!-- bar S -->
<!ENTITY barT		"T&#x0304;">	<!-- bar T -->
<!ENTITY barU		 "&#x016A;">	<!-- bar U -->
<!ENTITY barV		"V&#x0304;">	<!-- bar V -->
<!ENTITY barW		"W&#x0304;">	<!-- bar W -->
<!ENTITY barX		"X&#x0304;">	<!-- bar X -->
<!ENTITY barY		 "&#x0232;">	<!-- bar Y -->
<!ENTITY barZ		"Z&#x0304;">	<!-- bar Z -->
<!ENTITY bara		 "&#x0101;">	<!-- bar a -->
<!ENTITY barb		"b&#x0304;">	<!-- bar b -->
<!ENTITY barc		"c&#x0304;">	<!-- bar c -->
<!ENTITY bard		"d&#x0304;">	<!-- bar d -->
<!ENTITY bare		 "&#x0113;">	<!-- bar e -->
<!ENTITY barf		"f&#x0304;">	<!-- bar f -->
<!ENTITY barg		 "&#x1E21;">	<!-- bar g -->
<!ENTITY barh		"h&#x0304;">	<!-- bar h -->
<!ENTITY bari		 "&#x012B;">	<!-- bar i -->
<!ENTITY barj		"j&#x0304;">	<!-- bar j -->
<!ENTITY bark		"k&#x0304;">	<!-- bar k -->
<!ENTITY barl		"l&#x0304;">	<!-- bar l -->
<!ENTITY barm		"m&#x0304;">	<!-- bar m -->
<!ENTITY barn		"n&#x0304;">	<!-- bar n -->
<!ENTITY baro		 "&#x014D;">	<!-- bar o -->
<!ENTITY barp		"p&#x0304;">	<!-- bar p -->
<!ENTITY barq		"q&#x0304;">	<!-- bar q -->
<!ENTITY barr		"r&#x0304;">	<!-- bar r -->
<!ENTITY bars		"s&#x0304;">	<!-- bar s -->
<!ENTITY bart		"t&#x0304;">	<!-- bar t -->
<!ENTITY baru		 "&#x016B;">	<!-- bar u -->
<!ENTITY barv		"v&#x0304;">	<!-- bar v -->
<!ENTITY barw		"w&#x0304;">	<!-- bar w -->
<!ENTITY barx		"x&#x0304;">	<!-- bar x -->
<!ENTITY bary		 "&#x0233;">	<!-- bar y -->
<!ENTITY barz		"z&#x0304;">	<!-- bar z -->
<!ENTITY barAlpha	 "&#x1FB9;">	<!-- bar Alpha -->
<!ENTITY barIota	 "&#x1FD9;">	<!-- bar Iota -->
<!ENTITY barGamma	"&Gamma;&#x0304;">	<!-- bar Gamma -->
<!ENTITY barUpsilon	 "&#x1FE9;">	<!-- bar Upsilon -->
<!ENTITY baralpha	 "&#x1FB1;">	<!-- bar alpha -->
<!ENTITY barbeta	"&beta;&#x0304;">	<!-- bar beta -->
<!ENTITY bargamma	"&gamma;&#x0304;">	<!-- bar gamma -->
<!ENTITY bardelta	"&delta;&#x0304;">	<!-- bar delta -->
<!ENTITY barepsilon	"&epsilon;&#x0304;">	<!-- bar epsilon -->
<!ENTITY barzeta	"&zeta;&#x0304;">	<!-- bar zeta -->
<!ENTITY bareta		"&eta;&#x0304;">	<!-- bar eta -->
<!ENTITY bartheta	"&theta;&#x0304;">	<!-- bar theta -->
<!ENTITY bariota	 "&#x1FD1;">	<!-- bar iota -->
<!ENTITY barkappa	"&kappa;&#x0304;">	<!-- bar kappa -->
<!ENTITY barlambda	"&lambda;&#x0304;">	<!-- bar lambda -->
<!ENTITY barmu		"&mu;&#x0304;">	<!-- bar mu -->
<!ENTITY barnu		"&nu;&#x0304;">	<!-- bar nu -->
<!ENTITY barxi		"&xi;&#x0304;">	<!-- bar xi -->
<!ENTITY barpi		"&pi;&#x0304;">	<!-- bar pi -->
<!ENTITY barrho		"&rho;&#x0304;">	<!-- bar rho -->
<!ENTITY barsigma	"&sigma;&#x0304;">	<!-- bar sigma -->
<!ENTITY bartau		"&tau;&#x0304;">	<!-- bar tau -->
<!ENTITY barupsilon	 "&#x1FE1;">	<!-- bar upsilon -->
<!ENTITY barphi		"&phi;&#x0304;">	<!-- bar phi -->
<!ENTITY barchi		"&chi;&#x0304;">	<!-- bar chi -->
<!ENTITY barpsi		"&psi;&#x0304;">	<!-- bar psi -->
<!ENTITY baromega	"&omega;&#x0304;">	<!-- bar omega -->
<!ENTITY barvarepsilon	"&varepsilon;&#x0304;">	<!-- bar varepsilon -->
<!ENTITY barvartheta	"&vartheta;&#x0304;">	<!-- bar vartheta -->
<!ENTITY barvarpi	"&varpi;&#x0304;">	<!-- bar varpi -->
<!ENTITY barvarrho	"&varrho;&#x0304;">	<!-- bar varrho -->
<!ENTITY barvarsigma	"&varsigma;&#x0304;">	<!-- bar varsigma -->
<!ENTITY barvarphi	"&varphi;&#x0304;">	<!-- bar varphi -->
<!ENTITY barpartial	"&partial;&#x0304;">	<!-- bar partial -->
<!-- These are upright -->
<!ENTITY bar0		"0&#x0304;">	<!-- bar 0 -->
<!ENTITY bar1		"1&#x0304;">	<!-- bar 1 -->
<!ENTITY bar2		"2&#x0304;">	<!-- bar 2 -->
<!ENTITY bar3		"3&#x0304;">	<!-- bar 3 -->
<!ENTITY bar4		"4&#x0304;">	<!-- bar 4 -->
<!ENTITY bar5		"5&#x0304;">	<!-- bar 5 -->
<!ENTITY bar6		"6&#x0304;">	<!-- bar 6 -->
<!ENTITY bar7		"7&#x0304;">	<!-- bar 7 -->
<!ENTITY bar8		"8&#x0304;">	<!-- bar 8 -->
<!ENTITY bar9		"9&#x0304;">	<!-- bar 9 -->


<!-- dotted characters (in maths) -->
<!-- XXX The images for these are italic -->
<!ENTITY dotA		 "&#x0226;">	<!-- dot A -->
<!ENTITY dotB		 "&#x1E02;">	<!-- dot B -->
<!ENTITY dotC		 "&#x010A;">	<!-- dot C -->
<!ENTITY dotD		 "&#x1E0A;">	<!-- dot D -->
<!ENTITY dotE		 "&#x0116;">	<!-- dot E -->
<!ENTITY dotF		 "&#x1E1E;">	<!-- dot F -->
<!ENTITY dotG		 "&#x0120;">	<!-- dot G -->
<!ENTITY dotH		 "&#x1E22;">	<!-- dot H -->
<!ENTITY dotI		 "&#x0130;">	<!-- dot I -->
<!ENTITY dotJ		"J&#x0307;">	<!-- dot J -->
<!ENTITY dotK		"K&#x0307;">	<!-- dot K -->
<!ENTITY dotL		"L&#x0307;">	<!-- dot L -->
<!ENTITY dotM		 "&#x1E40;">	<!-- dot M -->
<!ENTITY dotN		 "&#x1E44;">	<!-- dot N -->
<!ENTITY dotO		 "&#x022E;">	<!-- dot O -->
<!ENTITY dotP		 "&#x1E56;">	<!-- dot P -->
<!ENTITY dotQ		"Q&#x0307;">	<!-- dot Q -->
<!ENTITY dotR		 "&#x1E58;">	<!-- dot R -->
<!ENTITY dotS		 "&#x1E60;">	<!-- dot S -->
<!ENTITY dotT		 "&#x1E6A;">	<!-- dot T -->
<!ENTITY dotU		"U&#x0307;">	<!-- dot U -->
<!ENTITY dotV		"V&#x0307;">	<!-- dot V -->
<!ENTITY dotW		 "&#x1E86;">	<!-- dot W -->
<!ENTITY dotX		 "&#x1E8A;">	<!-- dot X -->
<!ENTITY dotY		 "&#x1E8E;">	<!-- dot Y -->
<!ENTITY dotZ		 "&#x017B;">	<!-- dot Z -->
<!ENTITY dota		 "&#x0227;">	<!-- dot a -->
<!ENTITY dotb		 "&#x1E03;">	<!-- dot b -->
<!ENTITY dotc		 "&#x010B;">	<!-- dot c -->
<!ENTITY dotd		 "&#x1E0B;">	<!-- dot d -->
<!ENTITY dote		 "&#x0117;">	<!-- dot e -->
<!ENTITY dotf		 "&#x1E1F;">	<!-- dot f -->
<!ENTITY dotg		 "&#x0121;">	<!-- dot g -->
<!ENTITY doth		 "&#x1E23;">	<!-- dot h -->
<!ENTITY doti		"i&#x0307;">	<!-- dot i -->
<!ENTITY dotj		"j&#x0307;">	<!-- dot j -->
<!ENTITY dotk		"k&#x0307;">	<!-- dot k -->
<!ENTITY dotl		"l&#x0307;">	<!-- dot l -->
<!ENTITY dotm		 "&#x1E41;">	<!-- dot m -->
<!ENTITY dotn		 "&#x1E45;">	<!-- dot n -->
<!ENTITY doto		 "&#x022F;">	<!-- dot o -->
<!ENTITY dotp		 "&#x1E57;">	<!-- dot p -->
<!ENTITY dotq		"q&#x0307;">	<!-- dot q -->
<!ENTITY dotr		 "&#x1E59;">	<!-- dot r -->
<!ENTITY dots		 "&#x1E61;">	<!-- dot s -->
<!ENTITY dott		 "&#x1E6B;">	<!-- dot t -->
<!ENTITY dotu		"u&#x0307;">	<!-- dot u -->
<!ENTITY dotv		"v&#x0307;">	<!-- dot v -->
<!ENTITY dotw		 "&#x1E87;">	<!-- dot w -->
<!ENTITY dotx		 "&#x1E8B;">	<!-- dot x -->
<!ENTITY doty		 "&#x1E8F;">	<!-- dot y -->
<!ENTITY dotz		 "&#x017C;">	<!-- dot z -->
<!ENTITY zdotacc	 "&#x017C;">	<!-- z dot -->


<!ENTITY dotalpha	"&alpha;&#x0307;">	<!-- dot alpha -->
<!ENTITY dotbeta	"&beta;&#x0307;">	<!-- dot beta -->
<!ENTITY dotgamma	"&gamma;&#x0307;">	<!-- dot gamma -->
<!ENTITY dotdelta	"&delta;&#x0307;">	<!-- dot delta -->
<!ENTITY dotepsilon	"&epsilon;&#x0307;">	<!-- dot epsilon -->
<!ENTITY dotzeta	"&zeta;&#x0307;">	<!-- dot zeta -->
<!ENTITY doteta		"&eta;&#x0307;">	<!-- dot eta -->
<!ENTITY dottheta	"&theta;&#x0307;">	<!-- dot theta -->
<!ENTITY dotiota	"&iota;&#x0307;">	<!-- dot iota -->
<!ENTITY dotkappa	"&kappa;&#x0307;">	<!-- dot kappa -->
<!ENTITY dotlambda	"&lambda;&#x0307;">	<!-- dot lambda -->
<!ENTITY dotmu		"&mu;&#x0307;">	<!-- dot mu -->
<!ENTITY dotnu		"&nu;&#x0307;">	<!-- dot nu -->
<!ENTITY dotxi		"&xi;&#x0307;">	<!-- dot xi -->
<!ENTITY dotpi		"&pi;&#x0307;">	<!-- dot pi -->
<!ENTITY dotrho		"&rho;&#x0307;">	<!-- dot rho -->
<!ENTITY dotsigma	"&sigma;&#x0307;">	<!-- dot sigma -->
<!ENTITY dottau		"&tau;&#x0307;">	<!-- dot tau -->
<!ENTITY dotupsilon	"&upsilon;&#x0307;">	<!-- dot upsilon -->
<!ENTITY dotphi		"&phi;&#x0307;">	<!-- dot phi -->
<!ENTITY dotchi		"&chi;&#x0307;">	<!-- dot chi -->
<!ENTITY dotpsi		"&psi;&#x0307;">	<!-- dot psi -->
<!ENTITY dotomega	"&omega;&#x0307;">	<!-- dot omega -->
<!ENTITY dotvarepsilon	"&varepsilon;&#x0307;">	<!-- dot varepsilon -->
<!ENTITY dotvartheta	"&vartheta;&#x0307;">	<!-- dot vartheta -->
<!ENTITY dotvarpi	"&varpi;&#x0307;">	<!-- dot varpi -->
<!ENTITY dotvarrho	"&varrho;&#x0307;">	<!-- dot varrho -->
<!ENTITY dotvarsigma	"&varsigma;&#x0307;">	<!-- dot varsigma -->
<!ENTITY dotvarphi	"&varphi;&#x0307;">	<!-- dot varphi -->
<!ENTITY dotpartial	"&partial;&#x0307;">	<!-- dot partial -->
<!ENTITY dotell		"&ell;&#x0307;">	<!-- dot ell -->
<!ENTITY dotnabla	"&nabla;&#x0307;">	<!-- dot nabla -->

<!-- tilde characters (in maths) added 4/10 by Jo -->
<!-- XXX The images for these are italic -->
<!ENTITY tildeA		 "&#x00C3;">	<!-- tilde A -->
<!ENTITY tildeB		"B&#x0303;">	<!-- tilde B -->
<!ENTITY tildeC		"C&#x0303;">	<!-- tilde C -->
<!ENTITY tildeD		"D&#x0303;">	<!-- tilde D -->
<!ENTITY tildeE		 "&#x1EBC;">	<!-- tilde E -->
<!ENTITY tildeF		"F&#x0303;">	<!-- tilde F -->
<!ENTITY tildeG		"G&#x0303;">	<!-- tilde G -->
<!ENTITY tildeH		"H&#x0303;">	<!-- tilde H -->
<!ENTITY tildeI		 "&#x0128;">	<!-- tilde I -->
<!ENTITY tildeJ		"J&#x0303;">	<!-- tilde J -->
<!ENTITY tildeK		"K&#x0303;">	<!-- tilde K -->
<!ENTITY tildeL		"L&#x0303;">	<!-- tilde L -->
<!ENTITY tildeM		"M&#x0303;">	<!-- tilde M -->
<!ENTITY tildeN		 "&#x00D1;">	<!-- tilde N -->
<!ENTITY tildeO		"O&#x0303;">	<!-- tilde O -->
<!ENTITY tildeP		"P&#x0303;">	<!-- tilde P -->
<!ENTITY tildeQ		"Q&#x0303;">	<!-- tilde Q -->
<!ENTITY tildeR		"R&#x0303;">	<!-- tilde R -->
<!ENTITY tildeS		"S&#x0303;">	<!-- tilde S -->
<!ENTITY tildeT		"T&#x0303;">	<!-- tilde T -->
<!ENTITY tildeU		 "&#x0168;">	<!-- tilde U -->
<!ENTITY tildeV		 "&#x1E7C;">	<!-- tilde V -->
<!ENTITY tildeW		"W&#x0303;">	<!-- tilde W -->
<!ENTITY tildeX		"X&#x0303;">	<!-- tilde X -->
<!ENTITY tildeY		 "&#x1EF8;">	<!-- tilde Y -->
<!ENTITY tildeZ		"Z&#x0303;">	<!-- tilde Z -->
<!ENTITY tildea		 "&#x00E3;">	<!-- tilde a -->
<!ENTITY tildeb		"b&#x0303;">	<!-- tilde b -->
<!ENTITY tildec		"c&#x0303;">	<!-- tilde c -->
<!ENTITY tilded		"d&#x0303;">	<!-- tilde d -->
<!ENTITY tildee		 "&#x1EBD;">	<!-- tilde e -->
<!ENTITY tildef		"f&#x0303;">	<!-- tilde f -->
<!ENTITY tildeg		"g&#x0303;">	<!-- tilde g -->
<!ENTITY tildeh		"h&#x0303;">	<!-- tilde h -->
<!ENTITY tildei		 "&#x0129;">	<!-- tilde i -->
<!ENTITY tildej		"j&#x0303;">	<!-- tilde j -->
<!ENTITY tildek		"k&#x0303;">	<!-- tilde k -->
<!ENTITY tildel		"l&#x0303;">	<!-- tilde l -->
<!ENTITY tildem		"m&#x0303;">	<!-- tilde m -->
<!ENTITY tilden		 "&#x00F1;">	<!-- tilde n -->
<!ENTITY tildeo		"o&#x0303;">	<!-- tilde o -->
<!ENTITY tildep		"p&#x0303;">	<!-- tilde p -->
<!ENTITY tildeq		"q&#x0303;">	<!-- tilde q -->
<!ENTITY tilder		"r&#x0303;">	<!-- tilde r -->
<!ENTITY tildes		"s&#x0303;">	<!-- tilde s -->
<!ENTITY tildet		"t&#x0303;">	<!-- tilde t -->
<!ENTITY tildeu		 "&#x0169;">	<!-- tilde u -->
<!ENTITY tildev		 "&#x1E7D;">	<!-- tilde v -->
<!ENTITY tildew		"w&#x0303;">	<!-- tilde w -->
<!ENTITY tildex		"x&#x0303;">	<!-- tilde x -->
<!ENTITY tildey		 "&#x1EF9;">	<!-- tilde y -->
<!ENTITY tildez		"z&#x0303;">	<!-- tilde z -->
<!ENTITY tildeGamma	"&Gamma;&#x0303;">	<!-- tilde Gamma -->
<!ENTITY tildeDelta	"&Delta;&#x0303;">	<!-- tilde Delta -->
<!ENTITY tildeTheta	"&Theta;&#x0303;">	<!-- tilde Theta -->
<!ENTITY tildeLambda	"&Lambda;&#x0303;">	<!-- tilde Lambda -->
<!ENTITY tildeXi	"&Xi;&#x0303;">	<!-- tilde Xi -->
<!ENTITY tildePi	"&Pi;&#x0303;">	<!-- tilde Pi -->
<!ENTITY tildeSigma	"&Sigma;&#x0303;">	<!-- tilde Sigma -->
<!ENTITY tildeUpsilon	"&Upsilon;&#x0303;">	<!-- tilde Upsilon -->
<!ENTITY tildePhi	"&Phi;&#x0303;">	<!-- tilde Phi -->
<!ENTITY tildePsi	"&Psi;&#x0303;">	<!-- tilde Psi -->
<!ENTITY tildeOmega	"&Omega;&#x0303;">	<!-- tilde Omega -->
<!ENTITY tildealpha	"&alpha;&#x0303;">	<!-- tilde alpha -->
<!ENTITY tildebeta	"&beta;&#x0303;">	<!-- tilde beta -->
<!ENTITY tildegamma	"&gamma;&#x0303;">	<!-- tilde gamma -->
<!ENTITY tildedelta	"&delta;&#x0303;">	<!-- tilde delta -->
<!ENTITY tildeepsilon	"&epsilon;&#x0303;">	<!-- tilde epsilon -->
<!ENTITY tildezeta	"&zeta;&#x0303;">	<!-- tilde zeta -->
<!ENTITY tildeeta	"&eta;&#x0303;">	<!-- tilde eta -->
<!ENTITY tildetheta	"&theta;&#x0303;">	<!-- tilde theta -->
<!ENTITY tildeiota	"&iota;&#x0303;">	<!-- tilde iota -->
<!ENTITY tildekappa	"&kappa;&#x0303;">	<!-- tilde kappa -->
<!ENTITY tildelambda	"&lambda;&#x0303;">	<!-- tilde lambda -->
<!ENTITY tildemu	"&mu;&#x0303;">	<!-- tilde mu -->
<!ENTITY tildenu	"&nu;&#x0303;">	<!-- tilde nu -->
<!ENTITY tildexi	"&xi;&#x0303;">	<!-- tilde xi -->
<!ENTITY tildepi	"&pi;&#x0303;">	<!-- tilde pi -->
<!ENTITY tilderho	"&rho;&#x0303;">	<!-- tilde rho -->
<!ENTITY tildesigma	"&sigma;&#x0303;">	<!-- tilde sigma -->
<!ENTITY tildetau	"&tau;&#x0303;">	<!-- tilde tau -->
<!ENTITY tildeupsilon	"&upsilon;&#x0303;">	<!-- tilde upsilon -->
<!ENTITY tildephi	"&phi;&#x0303;">	<!-- tilde phi -->
<!ENTITY tildechi	"&chi;&#x0303;">	<!-- tilde chi -->
<!ENTITY tildepsi	"&psi;&#x0303;">	<!-- tilde psi -->
<!ENTITY tildeomega	"&omega;&#x0303;">	<!-- tilde omega -->
<!ENTITY tildevarepsilon "&varepsilon;&#x0303;">	<!-- tilde varepsilon -->
<!ENTITY tildevartheta	"&vartheta;&#x0303;">	<!-- tilde vartheta -->
<!ENTITY tildevarpi	"&varpi;&#x0303;">	<!-- tilde varpi -->
<!ENTITY tildevarrho	"&varrho;&#x0303;">	<!-- tilde varrho -->
<!ENTITY tildevarsigma	"&varsigma;&#x0303;">	<!-- tilde varsigma -->
<!ENTITY tildevarphi	"&varphi;&#x0303;">	<!-- tilde varphi -->
<!-- upright -->
<!ENTITY tilde0		"0&#x0303;">		<!-- 0 with tilde -->
<!ENTITY tilde1		"1&#x0303;">		<!-- 1 with tilde -->
<!ENTITY tilde2		"2&#x0303;">		<!-- 2 with tilde -->
<!ENTITY tilde3		"3&#x0303;">		<!-- 3 with tilde -->
<!ENTITY tilde4		"4&#x0303;">		<!-- 4 with tilde -->
<!ENTITY tilde5		"5&#x0303;">		<!-- 5 with tilde -->
<!ENTITY tilde6		"6&#x0303;">		<!-- 6 with tilde -->
<!ENTITY tilde7		"7&#x0303;">		<!-- 7 with tilde -->
<!ENTITY tilde8		"8&#x0303;">		<!-- 8 with tilde -->
<!ENTITY tilde9		"9&#x0303;">		<!-- 9 with tilde -->


<!-- hatted characters (in maths) -->
<!-- XXX The images for these are italic, of course -->
<!ENTITY hatA		 "&#x00C2;">	<!-- hat A -->
<!ENTITY hatB		"B&#x0302;">	<!-- hat B -->
<!ENTITY hatC		 "&#x0108;">	<!-- hat C -->
<!ENTITY hatD		"D&#x0302;">	<!-- hat D -->
<!ENTITY hatE		 "&#x00CA;">	<!-- hat E -->
<!ENTITY hatF		"F&#x0302;">	<!-- hat F -->
<!ENTITY hatG		 "&#x011C;">	<!-- hat G -->
<!ENTITY hatH		 "&#x0124;">	<!-- hat H -->
<!ENTITY hatI		 "&#x00CE;">	<!-- hat I -->
<!ENTITY hatJ		 "&#x0134;">	<!-- hat J -->
<!ENTITY hatK		"K&#x0302;">	<!-- hat K -->
<!ENTITY hatL		"L&#x0302;">	<!-- hat L -->
<!ENTITY hatM		"M&#x0302;">	<!-- hat M -->
<!ENTITY hatN		"N&#x0302;">	<!-- hat N -->
<!ENTITY hatO		 "&#x00D4;">	<!-- hat O -->
<!ENTITY hatP		"P&#x0302;">	<!-- hat P -->
<!ENTITY hatQ		"Q&#x0302;">	<!-- hat Q -->
<!ENTITY hatR		"R&#x0302;">	<!-- hat R -->
<!ENTITY hatS		 "&#x015C;">	<!-- hat S -->
<!ENTITY hatT		"T&#x0302;">	<!-- hat T -->
<!ENTITY hatU		 "&#x00DB;">	<!-- hat U -->
<!ENTITY hatV		"V&#x0302;">	<!-- hat V -->
<!ENTITY hatW		 "&#x0174;">	<!-- hat W -->
<!ENTITY hatX		"X&#x0302;">	<!-- hat X -->
<!ENTITY hatY		 "&#x0176;">	<!-- hat Y -->
<!ENTITY hatZ		 "&#x1E90;">	<!-- hat Z -->
<!ENTITY hata		 "&#x00E2;">	<!-- hat a -->
<!ENTITY hatb		"b&#x0302;">	<!-- hat b -->
<!ENTITY hatc		 "&#x0109;">	<!-- hat c -->
<!ENTITY hatd		"d&#x0302;">	<!-- hat d -->
<!ENTITY hate		 "&#x00EA;">	<!-- hat e -->
<!ENTITY hatf		"f&#x0302;">	<!-- hat f -->
<!ENTITY hatg		 "&#x011D;">	<!-- hat g -->
<!ENTITY hath		 "&#x0125;">	<!-- hat h -->
<!ENTITY hati		 "&#x00EE;">	<!-- hat i -->
<!ENTITY hatj		 "&#x0135;">	<!-- hat j -->
<!ENTITY hatk		"k&#x0302;">	<!-- hat k -->
<!ENTITY hatl		"l&#x0302;">	<!-- hat l -->
<!ENTITY hatm		"m&#x0302;">	<!-- hat m -->
<!ENTITY hatn		"n&#x0302;">	<!-- hat n -->
<!ENTITY hato		 "&#x00F4;">	<!-- hat o -->
<!ENTITY hatp		"p&#x0302;">	<!-- hat p -->
<!ENTITY hatq		"q&#x0302;">	<!-- hat q -->
<!ENTITY hatr		"r&#x0302;">	<!-- hat r -->
<!ENTITY hats		 "&#x015D;">	<!-- hat s -->
<!ENTITY hatt		"t&#x0302;">	<!-- hat t -->
<!ENTITY hatu		 "&#x00FB;">	<!-- hat u -->
<!ENTITY hatv		"v&#x0302;">	<!-- hat v -->
<!ENTITY hatw		 "&#x0175;">	<!-- hat w -->
<!ENTITY hatx		"x&#x0302;">	<!-- hat x -->
<!ENTITY haty		 "&#x0177;">	<!-- hat y -->
<!ENTITY hatz		 "&#x1E91;">	<!-- hat z -->

<!ENTITY hatGamma	"&Gamma;&#x0302;">	<!-- hat Gamma -->
<!ENTITY hatDelta	"&Delta;&#x0302;">	<!-- hat Delta -->
<!ENTITY hatTheta	"&Theta;&#x0302;">	<!-- hat Theta -->
<!ENTITY hatXi		"&Xi;&#x0302;">	<!-- hat Xi -->
<!ENTITY hatPi		"&Pi;&#x0302;">	<!-- hat Pi -->
<!ENTITY hatSigma	"&Sigma;&#x0302;">	<!-- hat Sigma -->
<!ENTITY hatUpsilon	"&Upsilon;&#x0302;">	<!-- hat Upsilon -->
<!ENTITY hatPhi		"&Phi;&#x0302;">	<!-- hat Phi -->
<!ENTITY hatPsi		"&Psi;&#x0302;">	<!-- hat Psi -->
<!ENTITY hatOmega	"&Omega;&#x0302;">	<!-- hat Omega -->

<!ENTITY hatalpha	"&alpha;&#x0302;">	<!-- hat alpha -->
<!ENTITY hatbeta	"&beta;&#x0302;">	<!-- hat beta -->
<!ENTITY hatgamma	"&gamma;&#x0302;">	<!-- hat gamma -->
<!ENTITY hatdelta	"&delta;&#x0302;">	<!-- hat delta -->
<!ENTITY hatepsilon	"&epsilon;&#x0302;">	<!-- hat epsilon -->
<!ENTITY hatzeta	"&zeta;&#x0302;">	<!-- hat zeta -->
<!ENTITY hateta		"&eta;&#x0302;">	<!-- hat eta -->
<!ENTITY hattheta	"&theta;&#x0302;">	<!-- hat theta -->
<!ENTITY hatiota	"&iota;&#x0302;">	<!-- hat iota -->
<!ENTITY hatkappa	"&kappa;&#x0302;">	<!-- hat kappa -->
<!ENTITY hatlambda	"&lambda;&#x0302;">	<!-- hat lambda -->
<!ENTITY hatmu		"&mu;&#x0302;">	<!-- hat mu -->
<!ENTITY hatnu		"&nu;&#x0302;">	<!-- hat nu -->
<!ENTITY hatxi		"&xi;&#x0302;">	<!-- hat xi -->
<!ENTITY hatpi		"&pi;&#x0302;">	<!-- hat pi -->
<!ENTITY hatrho		"&rho;&#x0302;">	<!-- hat rho -->
<!ENTITY hatsigma	"&sigma;&#x0302;">	<!-- hat sigma -->
<!ENTITY hattau		"&tau;&#x0302;">	<!-- hat tau -->
<!ENTITY hatupsilon	"&upsilon;&#x0302;">	<!-- hat upsilon -->
<!ENTITY hatphi		"&phi;&#x0302;">	<!-- hat phi -->
<!ENTITY hatchi		"&chi;&#x0302;">	<!-- hat chi -->
<!ENTITY hatpsi		"&psi;&#x0302;">	<!-- hat psi -->
<!ENTITY hatomega	"&omega;&#x0302;">	<!-- hat omega -->
<!ENTITY hatvarepsilon	"&varepsilon;&#x0302;">	<!-- hat varepsilon -->
<!ENTITY hatvartheta	"&vartheta;&#x0302;">	<!-- hat vartheta -->
<!ENTITY hatvarpi	"&varpi;&#x0302;">	<!-- hat varpi -->
<!ENTITY hatvarrho	"&varrho;&#x0302;">	<!-- hat varrho -->
<!ENTITY hatvarsigma	"&varsigma;&#x0302;">	<!-- hat varsigma -->
<!ENTITY hatvarphi	"&varphi;&#x0302;">	<!-- hat varphi -->

<!ENTITY hatell		"&ell;&#x0302;">	<!-- script l with hat -->
<!ENTITY hatimath	"&imath;&#x0302;">	<!-- dotless i with hat -->
<!ENTITY hatjmath	"&jmath;&#x0302;">	<!-- dotless j with hat -->
<!ENTITY hatpartial	"&partial;&#x0302;">	<!-- partial d. with hat -->

<!-- These are upright -->
<!ENTITY hat0		"0&#x0302;">	<!-- hat 0 -->
<!ENTITY hat1		"1&#x0302;">	<!-- hat 1 -->
<!ENTITY hat2		"2&#x0302;">	<!-- hat 2 -->
<!ENTITY hat3		"3&#x0302;">	<!-- hat 3 -->
<!ENTITY hat4		"4&#x0302;">	<!-- hat 4 -->
<!ENTITY hat5		"5&#x0302;">	<!-- hat 5 -->
<!ENTITY hat6		"6&#x0302;">	<!-- hat 6 -->
<!ENTITY hat7		"7&#x0302;">	<!-- hat 7 -->
<!ENTITY hat8		"8&#x0302;">	<!-- hat 8 -->
<!ENTITY hat9		"9&#x0302;">	<!-- hat 9 -->

<!-- Bold characters with hats -->
<!ENTITY bhatA		"&#x1D400;&#x0302;">	<!-- bold hat A -->
<!ENTITY bhatB		"&#x1D401;&#x0302;">	<!-- bold hat B -->
<!ENTITY bhatC		"&#x1D402;&#x0302;">	<!-- bold hat C -->
<!ENTITY bhatD		"&#x1D403;&#x0302;">	<!-- bold hat D -->
<!ENTITY bhatE		"&#x1D404;&#x0302;">	<!-- bold hat E -->
<!ENTITY bhatF		"&#x1D405;&#x0302;">	<!-- bold hat F -->
<!ENTITY bhatG		"&#x1D406;&#x0302;">	<!-- bold hat G -->
<!ENTITY bhatH		"&#x1D407;&#x0302;">	<!-- bold hat H -->
<!ENTITY bhatI		"&#x1D408;&#x0302;">	<!-- bold hat I -->
<!ENTITY bhatJ		"&#x1D409;&#x0302;">	<!-- bold hat J -->
<!ENTITY bhatK		"&#x1D40A;&#x0302;">	<!-- bold hat K -->
<!ENTITY bhatL		"&#x1D40B;&#x0302;">	<!-- bold hat L -->
<!ENTITY bhatM		"&#x1D40C;&#x0302;">	<!-- bold hat M -->
<!ENTITY bhatN		"&#x1D40D;&#x0302;">	<!-- bold hat N -->
<!ENTITY bhatO		"&#x1D40E;&#x0302;">	<!-- bold hat O -->
<!ENTITY bhatP		"&#x1D40F;&#x0302;">	<!-- bold hat P -->
<!ENTITY bhatQ		"&#x1D410;&#x0302;">	<!-- bold hat Q -->
<!ENTITY bhatR		"&#x1D411;&#x0302;">	<!-- bold hat R -->
<!ENTITY bhatS		"&#x1D412;&#x0302;">	<!-- bold hat S -->
<!ENTITY bhatT		"&#x1D413;&#x0302;">	<!-- bold hat T -->
<!ENTITY bhatU		"&#x1D414;&#x0302;">	<!-- bold hat U -->
<!ENTITY bhatV		"&#x1D415;&#x0302;">	<!-- bold hat V -->
<!ENTITY bhatW		"&#x1D416;&#x0302;">	<!-- bold hat W -->
<!ENTITY bhatX		"&#x1D417;&#x0302;">	<!-- bold hat X -->
<!ENTITY bhatY		"&#x1D418;&#x0302;">	<!-- bold hat Y -->
<!ENTITY bhatZ		"&#x1D419;&#x0302;">	<!-- bold hat Z -->
<!ENTITY bhata		"&#x1D41A;&#x0302;">	<!-- bold hat a -->
<!ENTITY bhatb		"&#x1D41B;&#x0302;">	<!-- bold hat b -->
<!ENTITY bhatc		"&#x1D41C;&#x0302;">	<!-- bold hat c -->
<!ENTITY bhatd		"&#x1D41D;&#x0302;">	<!-- bold hat d -->
<!ENTITY bhate		"&#x1D41E;&#x0302;">	<!-- bold hat e -->
<!ENTITY bhatf		"&#x1D41F;&#x0302;">	<!-- bold hat f -->
<!ENTITY bhatg		"&#x1D420;&#x0302;">	<!-- bold hat g -->
<!ENTITY bhath		"&#x1D421;&#x0302;">	<!-- bold hat h -->
<!ENTITY bhati		"&#x1D422;&#x0302;">	<!-- bold hat i -->
<!ENTITY bhatj		"&#x1D423;&#x0302;">	<!-- bold hat j -->
<!ENTITY bhatk		"&#x1D424;&#x0302;">	<!-- bold hat k -->
<!ENTITY bhatl		"&#x1D425;&#x0302;">	<!-- bold hat l -->
<!ENTITY bhatm		"&#x1D426;&#x0302;">	<!-- bold hat m -->
<!ENTITY bhatn		"&#x1D427;&#x0302;">	<!-- bold hat n -->
<!ENTITY bhato		"&#x1D428;&#x0302;">	<!-- bold hat o -->
<!ENTITY bhatp		"&#x1D429;&#x0302;">	<!-- bold hat p -->
<!ENTITY bhatq		"&#x1D42A;&#x0302;">	<!-- bold hat q -->
<!ENTITY bhatr		"&#x1D42B;&#x0302;">	<!-- bold hat r -->
<!ENTITY bhats		"&#x1D42C;&#x0302;">	<!-- bold hat s -->
<!ENTITY bhatt		"&#x1D42D;&#x0302;">	<!-- bold hat t -->
<!ENTITY bhatu		"&#x1D42E;&#x0302;">	<!-- bold hat u -->
<!ENTITY bhatv		"&#x1D42F;&#x0302;">	<!-- bold hat v -->
<!ENTITY bhatw		"&#x1D430;&#x0302;">	<!-- bold hat w -->
<!ENTITY bhatx		"&#x1D431;&#x0302;">	<!-- bold hat x -->
<!ENTITY bhaty		"&#x1D432;&#x0302;">	<!-- bold hat y -->
<!ENTITY bhatz		"&#x1D433;&#x0302;">	<!-- bold hat z -->

<!ENTITY overline0	"0&#x0305;">
<!ENTITY overline1	"1&#x0305;">
<!ENTITY overline2	"2&#x0305;">
<!ENTITY overline3	"3&#x0305;">
<!ENTITY overline4	"4&#x0305;">
<!ENTITY overline5	"5&#x0305;">
<!ENTITY overline6	"6&#x0305;">
<!ENTITY overline7	"7&#x0305;">
<!ENTITY overline8	"8&#x0305;">
<!ENTITY overline9	"9&#x0305;">

<!-- Vectors; characters with over arrow -->
<!-- XXX Again, the existing images are all italic -->
<!ENTITY vecA		"A&#x20D7;">	<!-- vec A -->
<!ENTITY vecB		"B&#x20D7;">	<!-- vec B -->
<!ENTITY vecC		"C&#x20D7;">	<!-- vec C -->
<!ENTITY vecD		"D&#x20D7;">	<!-- vec D -->
<!ENTITY vecE		"E&#x20D7;">	<!-- vec E -->
<!ENTITY vecF		"F&#x20D7;">	<!-- vec F -->
<!ENTITY vecG		"G&#x20D7;">	<!-- vec G -->
<!ENTITY vecH		"H&#x20D7;">	<!-- vec H -->
<!ENTITY vecI		"I&#x20D7;">	<!-- vec I -->
<!ENTITY vecJ		"J&#x20D7;">	<!-- vec J -->
<!ENTITY vecK		"K&#x20D7;">	<!-- vec K -->
<!ENTITY vecL		"L&#x20D7;">	<!-- vec L -->
<!ENTITY vecM		"M&#x20D7;">	<!-- vec M -->
<!ENTITY vecN		"N&#x20D7;">	<!-- vec N -->
<!ENTITY vecO		"O&#x20D7;">	<!-- vec O -->
<!ENTITY vecP		"P&#x20D7;">	<!-- vec P -->
<!ENTITY vecQ		"Q&#x20D7;">	<!-- vec Q -->
<!ENTITY vecR		"R&#x20D7;">	<!-- vec R -->
<!ENTITY vecS		"S&#x20D7;">	<!-- vec S -->
<!ENTITY vecT		"T&#x20D7;">	<!-- vec T -->
<!ENTITY vecU		"U&#x20D7;">	<!-- vec U -->
<!ENTITY vecV		"V&#x20D7;">	<!-- vec V -->
<!ENTITY vecW		"W&#x20D7;">	<!-- vec W -->
<!ENTITY vecX		"X&#x20D7;">	<!-- vec X -->
<!ENTITY vecY		"Y&#x20D7;">	<!-- vec Y -->
<!ENTITY vecZ		"Z&#x20D7;">	<!-- vec Z -->
<!ENTITY veca		"a&#x20D7;">	<!-- vec a -->
<!ENTITY vecb		"b&#x20D7;">	<!-- vec b -->
<!ENTITY vecc		"c&#x20D7;">	<!-- vec c -->
<!ENTITY vecd		"d&#x20D7;">	<!-- vec d -->
<!ENTITY vece		"e&#x20D7;">	<!-- vec e -->
<!ENTITY vecf		"f&#x20D7;">	<!-- vec f -->
<!ENTITY vecg		"g&#x20D7;">	<!-- vec g -->
<!ENTITY vech		"h&#x20D7;">	<!-- vec h -->
<!ENTITY veci		"i&#x20D7;">	<!-- vec i -->
<!ENTITY vecj		"j&#x20D7;">	<!-- vec j -->
<!ENTITY veck		"k&#x20D7;">	<!-- vec k -->
<!ENTITY vecl		"l&#x20D7;">	<!-- vec l -->
<!ENTITY vecm		"m&#x20D7;">	<!-- vec m -->
<!ENTITY vecn		"n&#x20D7;">	<!-- vec n -->
<!ENTITY veco		"o&#x20D7;">	<!-- vec o -->
<!ENTITY vecp		"p&#x20D7;">	<!-- vec p -->
<!ENTITY vecq		"q&#x20D7;">	<!-- vec q -->
<!ENTITY vecr		"r&#x20D7;">	<!-- vec r -->
<!ENTITY vecs		"s&#x20D7;">	<!-- vec s -->
<!ENTITY vect		"t&#x20D7;">	<!-- vec t -->
<!ENTITY vecu		"u&#x20D7;">	<!-- vec u -->
<!ENTITY vecv		"v&#x20D7;">	<!-- vec v -->
<!ENTITY vecw		"w&#x20D7;">	<!-- vec w -->
<!ENTITY vecx		"x&#x20D7;">	<!-- vec x -->
<!ENTITY vecy		"y&#x20D7;">	<!-- vec y -->
<!ENTITY vecz		"z&#x20D7;">	<!-- vec z -->

<!-- upright -->
<!ENTITY vec0		"0&#x20D7;">	<!-- vec 0 -->
<!ENTITY vec1		"1&#x20D7;">	<!-- vec 1 -->
<!ENTITY vec2		"2&#x20D7;">	<!-- vec 2 -->
<!ENTITY vec3		"3&#x20D7;">	<!-- vec 3 -->
<!ENTITY vec4		"4&#x20D7;">	<!-- vec 4 -->
<!ENTITY vec5		"5&#x20D7;">	<!-- vec 5 -->
<!ENTITY vec6		"6&#x20D7;">	<!-- vec 6 -->
<!ENTITY vec7		"7&#x20D7;">	<!-- vec 7 -->
<!ENTITY vec8		"8&#x20D7;">	<!-- vec 8 -->
<!ENTITY vec9		"9&#x20D7;">	<!-- vec 9 -->

<!-- XXX italic -->
<!ENTITY vecalpha	"&alpha;&#x20D7;">	<!-- vec alpha -->
<!ENTITY vecbeta	"&beta;&#x20D7;">	<!-- vec beta -->
<!ENTITY vecgamma	"&gamma;&#x20D7;">	<!-- vec gamma -->
<!ENTITY vecdelta	"&delta;&#x20D7;">	<!-- vec delta -->
<!ENTITY vecepsilon	"&epsilon;&#x20D7;">	<!-- vec epsilon -->
<!ENTITY veczeta	"&zeta;&#x20D7;">	<!-- vec zeta -->
<!ENTITY veceta		"&eta;&#x20D7;">	<!-- vec eta -->
<!ENTITY vectheta	"&theta;&#x20D7;">	<!-- vec theta -->
<!ENTITY veciota	"&iota;&#x20D7;">	<!-- vec iota -->
<!ENTITY veckappa	"&kappa;&#x20D7;">	<!-- vec kappa -->
<!ENTITY veclambda	"&lambda;&#x20D7;">	<!-- vec lambda -->
<!ENTITY vecmu		"&mu;&#x20D7;">		<!-- vec mu -->
<!ENTITY vecnu		"&nu;&#x20D7;">		<!-- vec nu -->
<!ENTITY vecxi		"&xi;&#x20D7;">		<!-- vec xi -->
<!ENTITY vecpi		"&pi;&#x20D7;">		<!-- vec pi -->
<!ENTITY vecrho		"&rho;&#x20D7;">	<!-- vec rho -->
<!ENTITY vecsigma	"&sigma;&#x20D7;">	<!-- vec sigma -->
<!ENTITY vectau		"&tau;&#x20D7;">	<!-- vec tau -->
<!ENTITY vecupsilon	"&upsilon;&#x20D7;">	<!-- vec upsilon -->
<!ENTITY vecphi		"&phi;&#x20D7;">	<!-- vec phi -->
<!ENTITY vecchi		"&chi;&#x20D7;">	<!-- vec chi -->
<!ENTITY vecpsi		"&psi;&#x20D7;">	<!-- vec psi -->
<!ENTITY vecomega	"&omega;&#x20D7;">	<!-- vec omega -->
<!ENTITY vecvarepsilon	"&varepsilon;&#x20D7;">	<!-- vec varepsilon -->
<!ENTITY vecvartheta	"&vartheta;&#x20D7;">	<!-- vec vartheta -->
<!ENTITY vecvarpi	"&varpi;&#x20D7;">	<!-- vec varpi -->
<!ENTITY vecvarrho	"&varrho;&#x20D7;">	<!-- vec varrho -->
<!ENTITY vecvarsigma	"&varsigma;&#x20D7;">	<!-- vec varsigma -->
<!ENTITY vecvarphi	"&varphi;&#x20D7;">	<!-- vec varphi -->
<!ENTITY vecpartial	"&partial;&#x20D7;">	<!-- vec partial -->
<!ENTITY vecell		"&ell;&#x20D7;">	<!-- vec ell -->
<!ENTITY vecimath	"&imath;&#x20D7;">	<!-- vec imath -->
<!ENTITY vecjmath	"&jmath;&#x20D7;">	<!-- vec jmath -->
<!ENTITY vecnabla	"&nabla;&#x20D7;">	<!-- vec nabla -->

<!ENTITY S		"&#x00A7;">	<!-- section sign -->
<!ENTITY P		"&#x00B6;">	<!-- paragraph sign -->
<!ENTITY hash		"#">		<!-- hash -->
<!ENTITY Angstrom	"&#x00C5;">	<!-- Angstrom sign -->
<!ENTITY quarter	"&#x00BC;">	<!-- 1/4 -->
<!ENTITY threequarter	"&#x00BE;">	<!-- 3/4 -->
<!ENTITY threehalves	"3&#x2044;2">	<!-- 3/2 -->
<!ENTITY fivehalves	"5&#x2044;2">	<!-- 5/2 -->
<!ENTITY sevenhalves	"7&#x2044;2">	<!-- 7/2 -->
<!ENTITY ninehalves	"9&#x2044;2">	<!-- 9/2 -->
<!ENTITY degree		"&#x00B0;">	<!-- degree sign -->
<!ENTITY ldots		"&#x2026;">	<!-- ellipsis -->
<!ENTITY cdots		"&#x22EF;">	<!-- central ellipsis -->
<!ENTITY cdot		"&#x22C5;">	<!-- central dot, despite Latin-2 -->

<!-- IOP defined LaTeX entities -->
<!ENTITY ddiff		"d">	<!-- Upright "d" for differential d -->
<!ENTITY eexp		"e">	<!-- Upright "e" for exponential e -->
<!ENTITY iimg		"i">	<!-- Upright "i" for imaginary i -->
<!ENTITY Tr		"Tr">	<!-- Upright "Tr" for Trace -->
<!ENTITY tr		"tr">	<!-- Upright "tr" for trace -->
<!ENTITY re		"Re">	<!-- Upright "Re" for real -->
<!ENTITY im		"Im">	<!-- Upright "Im" for imaginary -->

<!-- Greek letters -->
<!ENTITY Upsilon	"&#x03A5;">
<!ENTITY Chi		"&#x03A7;">
<!ENTITY epsilon	"&#x03F5;">	<!-- straight epsilon -->
<!ENTITY varepsilon	"&#x03B5;">	<!-- curly epsilon -->
<!ENTITY theta		"&#x03B8;">
<!ENTITY omicron	"&#x03BF;">
<!ENTITY vartheta	"&#x03D1;">
<!ENTITY varpi		"&#x03D6;">
<!ENTITY varrho		"&#x03F1;">
<!ENTITY varsigma	"&#x03DB;">
<!ENTITY upsilon	"&#x03C5;">
<!ENTITY phi		"&#x03D5;">
<!ENTITY varphi		"&#x03C6;">

<!-- Bold Greek letters -->
<!ENTITY bGamma		"&#x1D6AA;">
<!ENTITY bDelta		"&#x1D6AB;">
<!ENTITY bTheta		"&#x1D6AF;">
<!ENTITY bLambda	"&#x1D6B2;">
<!ENTITY bXi		"&#x1D6B5;">
<!ENTITY bPi		"&#x1D6B8;">
<!ENTITY bSigma		"&#x1D6BA;">
<!ENTITY bUpsilon	"&#x1D6BC;">
<!ENTITY bPhi		"&#x1D6BD;">
<!ENTITY bPsi		"&#x1D6BF;">
<!ENTITY bOmega		"&#x1D6C0;">
<!ENTITY bnabla		"&#x1D6C1;">

<!ENTITY balpha		"&#x1D6C2;">
<!ENTITY bbeta		"&#x1D6C3;">
<!ENTITY bgamma		"&#x1D6C4;">
<!ENTITY bdelta		"&#x1D6C5;">
<!ENTITY bepsilon	"&#x1D6DC;">	<!-- bold straight epsilon -->
<!ENTITY bvarepsilon	"&#x1D6C6;">	<!-- bold curly epsilon -->
<!ENTITY bzeta		"&#x1D6C7;">
<!ENTITY bfeta		"&#x1D6C8;">
<!ENTITY btheta		"&#x1D6C9;">
<!ENTITY bvartheta	"&#x1D6C9;"> <!-- XXX -->
<!ENTITY biota		"&#x1D6CA;">
<!ENTITY bkappa		"&#x1D6CB;">
<!ENTITY blambda	"&#x1D6CC;">
<!ENTITY bmu		"&#x1D6CD;">
<!ENTITY bnu		"&#x1D6CE;">
<!ENTITY bxi		"&#x1D6CF;">
<!ENTITY bpi		"&#x1D6D1;">
<!ENTITY bvarpi		"&#x1D6E1;">
<!ENTITY brho		"&#x1D6D2;">
<!ENTITY bvarrho	"&#x1D6E0;">
<!ENTITY bsigma		"&#x1D6D4;">
<!ENTITY bvarsigma	"&#x1D6D3;">	<!-- bold final sigma -->
<!ENTITY btau		"&#x1D6D5;">
<!ENTITY bupsilon	"&#x1D6D6;">
<!ENTITY bphi		"&#x1D6DF;">
<!ENTITY bvarphi	"&#x1D6D7;">
<!ENTITY bchi		"&#x1D6D8;">
<!ENTITY bpsi		"&#x1D6D9;">
<!ENTITY bomega		"&#x1D6DA;">

<!-- Miscellaneous maths characters -->
<!ENTITY hbar		"&#x210F;">	<!-- Planck's constant over 2 pi -->
<!ENTITY imath		"&#x1D6A4;">	<!-- Dotless i -->
<!ENTITY bimath		"&imath;">	<!-- (bold) imath -->
<!ENTITY jmath		"&#x1D6A5;">	<!-- Dotless j -->
<!ENTITY bjmath		"&jmath;">	<!-- (bold) jmath -->
<!ENTITY wp		"&#x2118;">	<!-- Weierstrass p -->
<!ENTITY Re		"&#x211C;">	<!-- Real -->
<!ENTITY Im		"&#x2111;">	<!-- Imaginary -->
<!ENTITY partial	"&#x2202;">	<!-- Partial differential -->
<!ENTITY bpartial	"&#x1D6DB;">	<!-- bold partial differential d -->
<!ENTITY infty		"&#x221E;">	<!-- Infinity -->
<!ENTITY binfty		"&infty;">	<!-- (bold) infinity -->
<!ENTITY emptyset	"&#x2205;">	<!-- Empty set -->
<!ENTITY surd		"&#x221A;">	<!-- Square root -->
<!ENTITY bot		"&#x22A5;">	<!-- Bottom -->
<!ENTITY Vert		"||">
<!ENTITY vert		"|">
<!ENTITY angle		"&#x2220;">	<!-- Angle -->
<!ENTITY triangle	"&#x25B3;">	<!-- Triangle -->
<!ENTITY backslash	"&#92;">		<!-- Backslash -->
<!ENTITY exists		"&#x2203;">	<!-- There exists -->
<!ENTITY neg		"&#x00AC;">	<!-- Negation -->
<!ENTITY lnot		"&#x00AC;">	<!-- Logicl not -->
<!ENTITY natural	"&#x266E;">	<!-- Musical natural sign -->
<!ENTITY clubsuit	"&#x2663;">	<!-- Black club suit -->
<!ENTITY diamondsuit	"&#x2662;">	<!-- White diamond suit -->
<!ENTITY heartsuit	"&#x2661;">	<!-- White diamond suit -->
<!ENTITY spadesuit	"&#x2660;">	<!-- Black spade suit -->
<!ENTITY oint		"&#x222E;">	<!-- Countour integral -->
<!-- XXX None of these codepoints are actually large, necessarily -->
<!ENTITY bigcap		"&#x2229;">	<!-- Large intersection -->
<!ENTITY bigcup		"&#x222A;">	<!-- Large union -->
<!ENTITY bigsqcup	"&#x2294;">	<!-- Large square union -->
<!ENTITY bigvee		"&#x2228;">	<!-- Large logical or -->
<!ENTITY bigwedge	"&#x2227;">	<!-- Large logical and -->
<!ENTITY bigodot	"&#x2299;">	<!-- Large circled dot -->

<!-- Binary operations -->
<!ENTITY mp		"&#x2213;">	<!-- Minus or plus -->
<!ENTITY pm		"&#x00B1;">	<!-- Plus or minus -->
<!ENTITY setminus	"&#x2216;">	<!-- Set minus -->
<!ENTITY diamond	"&#x2662;">	<!-- White diamond -->
<!ENTITY bullet		"&#x2022;">	<!-- Bullet -->
<!ENTITY div		"&#x00F7;">	<!-- Division -->
<!ENTITY triangleleft	"&#x25C3;">	<!-- Left pointing triangle -->
<!ENTITY triangleright	"&#x25B9;">	<!-- Right pointing triangle -->
<!ENTITY wr		"&#x2240;">	<!-- Wreath product -->
<!ENTITY bigcirc	"&#x25EF;">	<!-- Large circle -->
<!ENTITY bigtriangleup	"&#x25B3;">	<!-- Large up pointing triangle -->
<!ENTITY bigtriangledown "&#x25BD;">	<!-- Large down pointing triangle -->
<!ENTITY vee		"&#x2228;">	<!-- Logical or -->
<!ENTITY lor		"&#x2228;">	<!-- Logical or -->
<!ENTITY wedge		"&#x2227;">	<!-- Logical and -->
<!ENTITY land		"&#x2227;">	<!-- Logical and -->
<!ENTITY circle		"&#x25CB;">	<!-- White circle -->
<!ENTITY oslashed	"&#x2298;">	<!-- Slashed circle -->
<!ENTITY dag		"&#x2020;">	<!-- Dagger -->
<!ENTITY ddagger	"&#x2021;">	<!-- Double dagger -->
<!ENTITY ddag		"&#x2021;">	<!-- Double dagger -->

<!-- Relations -->
<!ENTITY leq		"&#x2A7D;">	<!-- less than or slanted equal -->
<!ENTITY geq		"&#x2A7E;">	<!-- greater than or slanted equal -->
<!ENTITY leqq		"&#x2266;">	<!-- less than over equal -->
<!ENTITY geqq		"&#x2267;">	<!-- gtr than over equal -->
<!ENTITY leqslant	"&#x2A7D;">	<!-- less than or slant equal -->
<!ENTITY geqslant	"&#x2A7E;">	<!-- gtr than or slant equal -->
<!ENTITY eqslantless	"&#x2A95;">	<!-- less than or slant equal above -->
<!ENTITY eqslantgtr	"&#x2A96;">	<!-- gtr than or slant equal above -->
<!ENTITY lesssim	"&#x2272;">	<!-- less than or equivalent -->
<!ENTITY gtrsim		"&#x2273;">	<!-- gtr than or equivalent -->
<!ENTITY lessapprox	"&#x2A85;">	<!-- less than or approximate -->
<!ENTITY gtrapprox	"&#x2A86;">	<!-- gtr then or approximate -->
<!ENTITY lessdot	"&#x22D6;">	<!-- less than with dot -->
<!ENTITY gtrdot		"&#x22D7;">	<!-- gtr than with dot -->
<!ENTITY muchlt		"&#x226A;">	<!-- much less than -->
<!ENTITY muchgt		"&#x226B;">	<!-- much greater than -->
<!ENTITY ll		"&#x226A;">	<!-- double less than -->
<!ENTITY gg		"&#x226B;">	<!-- double greater than -->
<!ENTITY lll		"&#x22D8;">	<!-- triple less than -->
<!ENTITY ggg		"&#x22D9;">	<!-- triple gtr than -->
<!ENTITY llless		"&#x22D8;">	<!-- triple less than -->
<!ENTITY gggtr		"&#x22D9;">	<!-- triple gtr than -->
<!ENTITY lessgtr	"&#x2276;">	<!-- less than or greater than -->
<!ENTITY gtrless	"&#x2277;">	<!-- gtr than or less than -->
<!ENTITY lesseqgtr	"&#x22DA;">	<!-- less than equal or greater than -->
<!ENTITY gtreqless	"&#x22DB;">	<!-- gtr than equal or less than -->
<!ENTITY lesseqqgtr	"&#x2A8B;">	<!-- less dbl equal or greater -->
<!ENTITY gtreqqless	"&#x2A8B;">	<!-- gtr dbl equal or less than -->

<!ENTITY bumpeq		"&#x224F;">	<!-- equals with bump above -->
<!ENTITY Bumpeq		"&#x224E;">	<!-- equals with bump above + below -->
<!ENTITY eqcirc		"&#x2256;">	<!-- equals with circle inside -->
<!ENTITY circeq		"&#x2257;">	<!-- equals with circle above -->
<!ENTITY doteq		"&#x2250;">	<!-- dot over equal -->
<!ENTITY Doteq		"&#x2251;">	<!-- equal with dot above and below -->
<!ENTITY doteqdot	"&#x2251;">	<!-- equal with dot above and below -->
<!ENTITY risingdotseq	"&#x2253;">	<!-- equal with dot NE and SW -->
<!ENTITY fallingdotseq	"&#x2252;">	<!-- equal with dot NW and SE -->
<!ENTITY backsim	"&#x223D;">	<!-- reversed tilde -->
<!ENTITY backsimeq	"&#x22CD;">	<!-- reversed tilde equals -->
<!ENTITY thicksim	"&#x223C;">	<!-- thick similar -->
<!ENTITY thickapprox	"&#x2248;">	<!-- thick approximate -->
<!ENTITY approxeq	"&#x224A;">	<!-- approximately equal -->
<!ENTITY triangleq	"&#x225C;">	<!-- equals with triangle above -->
<!ENTITY varpropto	"&#x221D;">	<!-- proportional to variant -->
<!ENTITY prec		"&#x227A;">	<!-- precedes -->
<!ENTITY succ		"&#x227B;">	<!-- succeeds -->
<!ENTITY preceq		"&#x2AAF;">	<!-- precedes or equal -->
<!ENTITY succeq		"&#x2AB0;">	<!-- succeeds or equal -->
<!ENTITY preccurlyeq	"&#x227C;">	<!-- precedes or curly equal -->
<!ENTITY succcurlyeq	"&#x227D;">	<!-- succeeds or curly equal -->
<!ENTITY curlyeqprec	"&#x22DE;">	<!-- equal or precedes -->
<!ENTITY curlyeqsucc	"&#x22DF;">	<!-- equal or succeeds -->
<!ENTITY precsim	"&#x227E;">	<!-- precedes or equivalent -->
<!ENTITY succsim	"&#x227F;">	<!-- succeeds or equivalent -->
<!ENTITY precapprox	"&#x2AB7;">	<!-- precedes or approximate -->
<!ENTITY succapprox	"&#x2AB8;">	<!-- succeeds or approximate -->
<!ENTITY subset		"&#x2282;">	<!-- subset -->
<!ENTITY supset		"&#x2283;">	<!-- superset -->
<!ENTITY subseteq	"&#x2286;">	<!-- subset or equal -->
<!ENTITY supseteq	"&#x2287;">	<!-- superset or equal -->
<!ENTITY sqsubseteq	"&#x2291;">	<!-- square subset or equal -->
<!ENTITY sqsupseteq	"&#x2292;">	<!-- square superset or equal -->
<!ENTITY subseteqq	"&#x2AC5;">	<!-- subset over equals -->
<!ENTITY supseteqq	"&#x2AC6;">	<!-- superset over equals -->
<!ENTITY sqsubset	"&#x228F;">	<!-- square subset -->
<!ENTITY Subset		"&#x22D0;">	<!-- double subset -->
<!ENTITY Supset		"&#x22D1;">	<!-- double superset -->
<!ENTITY sqsupset	"&#x2290;">	<!-- square superset -->
<!ENTITY smallsetminus	"&#x2216;">	<!-- set minus (should be small) -->
<!ENTITY doublecap	"&#x22D2;">	<!-- double intersection -->
<!ENTITY doublecup	"&#x22D3;">	<!-- double union -->
<!ENTITY pitchfork	"&#x22D4;">	<!-- proper intersection -->
<!ENTITY in		"&#x220A;">	<!-- element of -->
<!ENTITY owns		"&#x220D;">	<!-- contains -->
<!ENTITY parallel	"&#x2225;">	<!-- parallel to -->
<!ENTITY nparallel	"&#x2226;">	<!-- not parallel -->
<!ENTITY shortparallel	"&#x2225;">	<!-- (not short) parallel -->
<!ENTITY nshortparallel	"&#x2226;">	<!-- (not short) not parallel -->
<!ENTITY simeq		"&#x2243;">	<!-- similar or equal -->
<!ENTITY approx		"&#x2248;">	<!-- appromiately equal -->
<!ENTITY propto		"&#x221D;">	<!-- proportional to -->

<!-- Negated relations -->
<!ENTITY notlt		"&#x226E;">	<!-- not less than -->
<!ENTITY notgt		"&#x226F;">	<!-- not greater than -->
<!ENTITY notleq		"&#x2270;">	<!-- not less than or equal -->
<!ENTITY notgeq		"&#x2271;">	<!-- not greater than or equal -->
<!ENTITY nleqq		"&#x2266;&#x0338;">	<!-- not less double equal -->
<!ENTITY ngeqq		"&#x2267;&#x0338;">	<!-- not gtr double equal -->
<!ENTITY nless		"&#x226E;">	<!-- not less than -->
<!ENTITY ngtr		"&#x226F;">	<!-- not gtr than -->
<!ENTITY nleq		"&#x2270;">	<!-- not less than or equal -->
<!ENTITY ngeq		"&#x2271;">	<!-- not gtr than or equal -->
<!ENTITY nleqslant	"&#x2A7D;&#x0338;">	<!-- not less slant equal -->
<!ENTITY ngeqslant	"&#x2A7E;&#x0338;">	<!-- not less slant equal -->
<!ENTITY lneq		"&#x2A87;">	<!-- less than over single not equal -->
<!ENTITY gneq		"&#x2A88;">	<!-- gtr than over single not equal -->
<!ENTITY lneqq		"&#x2268;">	<!-- less than over dbl not equal -->
<!ENTITY gneqq		"&#x2269;">	<!-- gtr than over dbl not equal -->
<!ENTITY lvertneqq	"&#x2268;">	<!-- less than over dbl v not equal -->
<!ENTITY gvertneqq	"&#x2269;">	<!-- gtr than over dbl v not equal -->
<!ENTITY lnapprox	"&#x2A89;">	<!-- less than, not approximate -->
<!ENTITY gnapprox	"&#x2A8A;">	<!-- gtr than, not approximate -->

<!ENTITY notprec	"&#x2280;">	<!-- not preceding -->
<!ENTITY notsucc	"&#x2281;">	<!-- not succeeding -->
<!ENTITY notpreceq	"&#x22E0;">	<!-- not preceding or equal -->
<!ENTITY notsucceq	"&#x22E1;">	<!-- not succeeding or equal -->
<!ENTITY nprec		"&#x2280;">	<!-- not precedes -->
<!ENTITY nsucc		"&#x2281;">	<!-- not succeeds -->
<!ENTITY npreceq	"&#x2AAF;&#x0338;">	<!-- not precedes or equal -->
<!ENTITY nsucceq	"&#x2AB0;&#x0338;">	<!-- not succeeds or equal -->
<!ENTITY precneqq	"&#x2AB5;">	<!-- precedes over not equal -->
<!ENTITY succneqq	"&#x2AB6;">	<!-- succeeds over not equal -->
<!ENTITY precnsim	"&#x22E8;">	<!-- precedes but not equivalent -->
<!ENTITY succnsim	"&#x22E9;">	<!-- succeeds but not equivalent -->
<!ENTITY precnapprox	"&#x2AB9;">	<!-- precedes over not almost equal -->
<!ENTITY succnapprox	"&#x2ABA;">	<!-- succeeds over not almost equal -->
<!ENTITY notsubset	"&#x2284;">	<!-- not subset -->
<!ENTITY notsupset	"&#x2285;">	<!-- not superset -->
<!ENTITY notsubseteq	"&#x2288;">	<!-- not subset or equal -->
<!ENTITY notsupseteq	"&#x2289;">	<!-- not superset or equal -->
<!ENTITY notsqsubseteq	"&#x22E2;">	<!-- not square subset or equal -->
<!ENTITY notsqsupseteq	"&#x22E3;">	<!-- not square superset or equal -->
<!ENTITY nsubseteq	"&#x2288;">	<!-- not subset or equal -->
<!ENTITY nsupseteq	"&#x2289;">	<!-- not superset or equal -->
<!ENTITY nsubseteqq	"&#x2AC5;&#x0338;">	<!-- not subset or dbl eq -->
<!ENTITY nsupseteqq	"&#x2AC6;&#x0338;">	<!-- not superset or dbl eq -->
<!ENTITY subsetneq	"&#x228A;">	<!-- subset over single not eq -->
<!ENTITY supsetneq	"&#x228B;">	<!-- superset over single not eq -->
<!ENTITY varsubsetneq	"&#x228A;">	<!-- subset over single not eq var -->
<!ENTITY varsupsetneq	"&#x228B;">	<!-- superset over single not eq var -->
<!ENTITY subsetneqq	"&#x2ACB;">	<!-- subset over double not eq -->
<!ENTITY supsetneqq	"&#x2ACC;">	<!-- superset over double not eq -->
<!ENTITY varsubsetneqq	"&#x2ACB;">	<!-- subset over double not eq var -->
<!ENTITY varsupsetneqq	"&#x2ACC;">	<!-- superset over double not eq var -->
<!ENTITY noteq		"&#x2260;">	<!-- not equal -->
<!ENTITY neq		"&#x2260;">	<!-- not equal -->
<!ENTITY notequiv	"&#x2262;">	<!-- not identical -->
<!ENTITY notsim		"&#x2241;">	<!-- not similar -->
<!ENTITY notsimeq	"&#x2244;">	<!-- not similar or equal -->
<!ENTITY notapprox	"&#x2249;">	<!-- not apprpximately equal -->
<!ENTITY notcong	"&#x2247;">	<!-- not approximate or equal -->
<!ENTITY notasymp	"&#x226D;">	<!-- not equivalent -->

<!-- Arrows -->
<!ENTITY leftarrow		"&#x2190;">	<!-- left arrow -->
  <!ENTITY gets			"&#x2190;">	<!-- left arrow -->
<!ENTITY rightarrow		"&#x2192;">	<!-- right arrow -->
  <!ENTITY to			"&#x2192;">	<!-- right arrow -->
<!ENTITY uparrow		"&#x2191;">	<!-- up arrow -->
<!ENTITY downarrow		"&#x2193;">	<!-- down arrow -->
<!ENTITY leftrightarrow		"&#x2194;">	<!-- left-right arrow -->
<!ENTITY updownarrow		"&#x2195;">	<!-- up-down arrow -->
<!ENTITY Leftarrow		"&#x21D0;">	<!-- left double arrow -->
<!ENTITY Rightarrow		"&#x21D2;">	<!-- right double arrow -->
<!ENTITY Uparrow		"&#x21D1;">	<!-- up double arrow -->
<!ENTITY Downarrow		"&#x21D3;">	<!-- down double arrow -->
<!ENTITY Leftrightarrow		"&#x21D4;">	<!-- left-right double arrow -->
<!ENTITY Updownarrow		"&#x21D5;">	<!-- up-down double arrow -->
<!ENTITY Lleftarrow		"&#x21DA;">	<!-- left triple arrow -->
<!ENTITY Rrightarrow		"&#x21DB;">	<!-- right triple arrow -->
<!ENTITY hookleftarrow		"&#x21A9;">	<!-- left hooked arrow -->
<!ENTITY hookrightarrow		"&#x21AA;">	<!-- right hooked arrow -->
<!ENTITY longleftarrow		"&#x27F5;">	<!-- left long arrow -->
<!ENTITY longrightarrow		"&#x27F6;">	<!-- right long arrow -->
<!ENTITY longleftrightarrow	"&#x27F7;">	<!-- left-right long arrow -->
<!ENTITY Longleftarrow		"&#x27F8;">	<!-- left long double arrow -->
<!ENTITY Longrightarrow		"&#x27F9;">	<!-- right long double arrow -->
<!ENTITY Longleftrightarrow	"&#x27FA;">	<!-- left-rt long dbl arrow -->
<!ENTITY leftleftarrows		"&#x21C7;">	<!-- left arrow pair -->
<!ENTITY rightrightarrows	"&#x21C9;">	<!-- right arrow pair -->
<!ENTITY upuparrows		"&#x21C8;">	<!-- up arrow pair -->
<!ENTITY downdownarrows		"&#x21CA;">	<!-- down arrow pair -->
<!ENTITY leftrightarrows	"&#x21C6;">	<!-- left over right arrow -->
<!ENTITY rightleftarrows	"&#x21C4;">	<!-- right over left arrow -->
<!ENTITY twoheadleftarrow	"&#x219E;">	<!-- left 2-head arrow -->
<!ENTITY twoheadrightarrow	"&#x21A0;">	<!-- right 2-head arrow -->
<!ENTITY leftarrowtail		"&#x21A2;">	<!-- left tailed arrow -->
<!ENTITY rightarrowtail		"&#x21A3;">	<!-- right tailed arrow -->
<!ENTITY looparrowleft		"&#x21AB;">	<!-- left looped arrow -->
<!ENTITY looparrowright		"&#x21AC;">	<!-- right looped arrow -->
<!ENTITY curvearrowleft		"&#x21B6;">	<!-- left curved arrow -->
<!ENTITY curvearrowright	"&#x21B7;">	<!-- right curved arrow -->
<!ENTITY circlearrowleft	"&#x21BA;">	<!-- left circle arrow -->
<!ENTITY circlearrowright	"&#x21BB;">	<!-- right circle arrow -->
<!ENTITY Lsh			"&#x21B0;">	<!-- up arrow left head -->
<!ENTITY Rsh			"&#x21B1;">	<!-- up arrow right head -->
<!ENTITY rightsquigarrow	"&#x219D;">	<!-- right squiggle arrow -->
<!ENTITY leftrightsquigarrow	"&#x21AD;">	<!-- left-right squiggle arr -->
<!ENTITY nleftarrow		"&#x219A;">	<!-- not left arrow -->
<!ENTITY nrightarrow		"&#x219B;">	<!-- not right arrow -->
<!ENTITY nLeftarrow		"&#x21CD;">	<!-- not left double arrow -->
<!ENTITY nRightarrow		"&#x21CF;">	<!-- not right double arrow -->
<!ENTITY nleftrightarrow	"&#x21AE;">	<!-- not left-right arrow -->
<!ENTITY nLeftrightarrow	"&#x21CE;">	<!-- not left-right dbl arr -->
<!ENTITY nearrow		"&#x2197;">	<!-- northeast arrow -->
<!ENTITY searrow		"&#x2199;">	<!-- southeast arrow -->
<!ENTITY swarrow		"&#x2198;">	<!-- southwest arrow -->
<!ENTITY nwarrow		"&#x2196;">	<!-- northwest arrow -->
<!ENTITY rightharpoonup		"&#x21C0;">	<!-- right harpoon up head -->
<!ENTITY rightharpoondown	"&#x21C1;">	<!-- right harpoon down head -->
<!ENTITY leftharpoonup		"&#x21BC;">	<!-- left harpoon up head -->
<!ENTITY leftharpoondown	"&#x21BD;">	<!-- left harpoon down head -->
<!ENTITY upharpoonleft		"&#x21BF;">	<!-- up harpoon left head -->
<!ENTITY upharpoonright		"&#x21BE;">	<!-- up harpoon right head -->
  <!ENTITY restriction		"&#x21BE;">	<!-- up harpoon right head -->
<!ENTITY downharpoonleft	"&#x21C3;">	<!-- down harpoon left head -->
<!ENTITY downharpoonright	"&#x21C2;">	<!-- down harpoon right head -->
<!ENTITY rightleftharpoons	"&#x21CC;">	<!-- right harpoon over left -->
<!ENTITY leftrightharpoons	"&#x21CB;">	<!-- left over right harpoon -->
<!ENTITY mapsto			"&#x21A6;">	<!-- maps to -->
<!ENTITY longmapsto		"&#x27FC;">	<!-- mapsto long -->
<!ENTITY multimap		"&#x22B8;">	<!-- multimap -->


<!-- Openings and closings -->
<!ENTITY lbrack		"[">		<!-- left bracket -->
<!ENTITY rbrack		"]">		<!-- right bracket -->
<!ENTITY lbrace		"{">		<!-- left curly brace -->
<!ENTITY rbrace		"}">		<!-- right curly brace -->
<!ENTITY langle		"&#x27E8;">	<!-- left angle bracket -->
<!ENTITY rangle		"&#x27E9;">	<!-- right angle bracket -->
<!ENTITY lchevron	"&#x2039;">	<!-- left chevron -->
<!ENTITY rchevron	"&#x203A;">	<!-- right chevron -->
<!ENTITY ldchevron	"&#x00AB;">	<!-- left double chevron -->
<!ENTITY rdchevron	"&#x00BB;">	<!-- right double chevron -->
<!ENTITY lquot		"&#x2018;">	<!-- left quote -->
<!ENTITY rquot		"&#x2019;">	<!-- right quote -->

<!-- Things which are supposed to be in a upright face -->
<!ENTITY arccos		" arccos "> 
<!ENTITY arcsin		" arcsin "> 
<!ENTITY arctan		" arctan "> 
<!ENTITY arg		" arg "> 
<!ENTITY cos		" cos "> 
<!ENTITY cosh		" cosh "> 
<!ENTITY cot		" cot "> 
<!ENTITY coth		" coth "> 
<!ENTITY csc		" csc "> 
<!ENTITY det		" det "> 
<!ENTITY dim		" dim "> 
<!ENTITY exp		" exp "> 
<!ENTITY gcd		" gcd "> 
<!ENTITY hom		" hom "> 
<!ENTITY inf		" inf "> 
<!ENTITY ker		" ker "> 
<!ENTITY lim		" lim "> 
<!ENTITY liminf		" liminf "> 
<!ENTITY limsup		" limsup "> 
<!ENTITY ln		" ln "> 
<!ENTITY log		" log "> 
<!ENTITY max		" max "> 
<!ENTITY min		" min "> 
<!ENTITY Pr		" Pr "> 
<!ENTITY sec		" sec "> 
<!ENTITY sin		" sin "> 
<!ENTITY sinh		" sinh "> 
<!ENTITY tan		" tan "> 
<!ENTITY tanh		" tanh "> 

<!-- Miscellaneous -->
	<!-- greek -->
<!ENTITY digamma	"&#x03DC;">	<!-- digamma -->
<!ENTITY varkappa	"&#x03F0;">	<!-- variant kappa -->
<!ENTITY mho		"&#x2127;">	<!-- inverted ohm -->
<!ENTITY backepsilon	"&#x03F6;">	<!-- reversed epsilon -->
<!ENTITY hatnabla	"&nabla;&#x0302;">	<!-- nabla with hat -->
<!ENTITY bvarzeta	"&#x1D6C7;">		<!-- bold zeta (no UCS var) -->
<!ENTITY bitGamma	"&#x1D71E;">		<!-- bold italic Gamma -->
<!ENTITY bitDelta	"&#x1D71F;">		<!-- bold italic Delta -->
<!ENTITY bitLambda	"&#x1D726;">		<!-- bold italic Lambda -->
<!ENTITY bitPi		"&#x1D72B;">		<!-- bold italic Pi -->
<!ENTITY bitTheta	"&#x1D72D;">		<!-- bold italic Theta -->
<!ENTITY bitSigma	"&#x1D72E;">		<!-- bold italic Sigma -->
<!ENTITY bitUpsilon	"&#x1D730;">		<!-- bold italic Upsilon -->
<!ENTITY bitPhi		"&#x1D731;">		<!-- bold italic Phi -->
<!ENTITY bitXi		"&#x1D732;">		<!-- bold italic Xi -->
<!ENTITY bitPsi		"&#x1D733;">		<!-- bold italic Psi -->
<!ENTITY bitOmega	"&#x1D734;">		<!-- bold italic Omega -->
<!ENTITY itGamma	"&#x1D6E4;">		<!-- italic Gamma -->
<!ENTITY itDelta	"&#x1D6E5;">		<!-- italic Delta -->
<!ENTITY itLambda	"&#x1D6EC;">		<!-- italic Lambda -->
<!ENTITY itPi		"&#x1D6F1;">		<!-- italic Pi -->
<!ENTITY itTheta	"&#x1D6F3;">		<!-- italic Theta -->
<!ENTITY itSigma	"&#x1D6F4;">		<!-- italic Sigma -->
<!ENTITY itUpsilon	"&#x1D6F6;">		<!-- italic Upsilon -->
<!ENTITY itPhi		"&#x1D6F7;">		<!-- italic Phi -->
<!ENTITY itXi		"&#x1D6F8;">		<!-- italic Xi -->
<!ENTITY itPsi		"&#x1D6F9;">		<!-- italic Psi -->
<!ENTITY itOmega	"&#x1D6FA;">		<!-- italic Omega -->
	<!-- letter-like -->
<!ENTITY hslash		"&#x210F;">	<!-- planck constant over 2 pi -->
<!ENTITY circledS	"&#x24C8;">	<!-- S in circle -->
<!ENTITY Finv		"&#x2132;">	<!-- turned F -->
<!ENTITY Game		"&#x2141;">	<!-- turned G -->
	<!-- geometric shapes -->
<!ENTITY diagup		"&#x2571;">	<!-- diagonal line upwards -->
<!ENTITY diagdown	"&#x2572;">	<!-- diagonal line downwards -->
<!ENTITY smallsmile	"&#x2323;">	<!-- small up curve -->
<!ENTITY smallfrown	"&#x2322;">	<!-- small down curve -->
<!ENTITY vartriangle	"&#x25B5;">	<!-- var triangle -->
<!ENTITY triangledown	"&#x25BD;">	<!-- down triangle -->
<!ENTITY vartriangleleft "&#x22B2;">	<!-- left var triangle -->
<!ENTITY trianglelefteq	"&#x22B4;">	<!-- triangle left or equal -->
<!ENTITY vartriangleright "&#x22B3;">	<!-- right var triangle -->
<!ENTITY trianglerighteq "&#x22B5;">	<!-- triangle right or equal -->
<!ENTITY ntriangleleft	"&#x22EA;">	<!-- not left triangle -->
<!ENTITY ntriangleright	"&#x22EB;">	<!-- not right triangle -->
<!ENTITY ntrianglelefteq	"&#x22EC;">	<!-- not left triangle eq -->
<!ENTITY ntrianglerighteq	"&#x22ED;">	<!-- not right triangle eq -->
<!ENTITY blacktriangle	"&#x25B4;">	<!-- up black triangle -->
<!ENTITY blacktriangledown	"&#x25BE;">	<!-- down black triangle -->
<!ENTITY blacktriangleleft	"&#x25C2;">	<!-- left black triangle -->
<!ENTITY blacktriangleright	"&#x25B8;">	<!-- right black triangle -->
<!ENTITY blacksquare	"&#x25A0;">	<!-- black square -->
<!ENTITY lozenge	"&#x25CA;">	<!-- lozenge -->
<!ENTITY blacklozenge	"&#x29EB;">	<!-- black lozenge -->
<!ENTITY bigstar	"&#x2605;">	<!-- big star -->
	<!-- enclosed -->
<!ENTITY boxminus	"&#x229F;">	<!-- minus sign in box -->
<!ENTITY boxtimes	"&#x22A0;">	<!-- times sign in box -->
<!ENTITY boxdot		"&#x22A1;">	<!-- dot in box -->
<!ENTITY boxplus	"&#x229E;">	<!-- plus sign in box -->
<!ENTITY circleddash	"&#x229D;">	<!-- circled dash -->
<!ENTITY circledast	"&#x229B;">	<!-- circled asterisk -->
<!ENTITY circledcirc	"&#x229A;">	<!-- circled circle -->

	<!-- misc -->
<!ENTITY measuredangle	"&#x2221;">	<!-- measured angle -->
<!ENTITY nexists	"&#x2204;">	<!-- there does not exist -->
<!ENTITY backprime	"&#x2035;">	<!-- reversed prime -->
<!ENTITY varnothing	"&#x2300;">	<!-- diameter -->
<!ENTITY sphericalangle	"&#x2222;">	<!-- spherical angle -->
<!ENTITY complement	"&#x2201;">	<!-- complement -->
<!ENTITY dotplus	"&#x2214;">	<!-- plus sign with dot above -->
<!ENTITY barwedge	"&#x2305;">	<!-- projective -->
<!ENTITY doublebarwedge	"&#x2306;">	<!-- perspective -->
<!ENTITY divideontimes	"&#x22C7;">	<!-- divide/times overprint -->
<!ENTITY leftthreetimes	"&#x22CB;">	<!-- left semidirect product -->
<!ENTITY rightthreetimes "&#x22CC;">	<!-- right semidirect product -->
<!ENTITY curlywedge	"&#x22CF;">	<!-- curly logical and -->
<!ENTITY curlyvee	"&#x22CE;">	<!-- curly logical or -->
<!ENTITY centerdot	"&#x00B7;">	<!-- central dot -->
<!ENTITY intercal	"&#x22BA;">	<!-- intercalate -->
<!ENTITY between	"&#x226C;">	<!-- between -->
<!ENTITY therefore	"&#x2234;">	<!-- therefore -->
<!ENTITY because	"&#x2235;">	<!-- because -->
<!ENTITY shortmid	"&#x2223;">	<!-- (not short) divides -->
<!ENTITY nshortmid	"&#x2224;">	<!-- (not short) does not divide -->

<!-- Received -->                                          
<!ENTITY received  "Received ">                  
<!ENTITY finalform  ", in final form ">          
<!ENTITY accepted  ", accepted for publication ">
<!ENTITY online  ", online ">                    


<!ENTITY bdot		"&#x2219;">		<!-- bold middot/bullet -->
<!ENTITY bell		"&#x1D4F5;">		<!-- bold ell -->
<!ENTITY btimes		"&times;">		<!-- (bold) times sign -->

<!ENTITY sqrt2		"sqrt2">		<!-- XXX "&#x221A;2" ??? -->
<!ENTITY sqrt3		"sqrt3">		<!-- XXX "&#x221A;3" ??? -->

<!-- AAS characters -->                                          
<!ENTITY angl0		"&#x3008;">		<!-- Left angle bracket (wide) -->
<!ENTITY angr0		"&#x3009;">		<!-- Right angle bracket (wide) -->
<!ENTITY arcdeg		"&#x00B0;">		<!-- Arc degrees -->
<!ENTITY arcmin		"&#x2032;">		<!-- Arc minutes -->
<!ENTITY arcsec		"&#x2033;">		<!-- Arc seconds -->
<!ENTITY sun		"&#x2609;">		<!-- Sun symbol -->
<!ENTITY mercury	"&#x263F;">		<!-- Mercury symbol -->
<!ENTITY venus		"&#x2640;">		<!-- Venus symbol -->
<!ENTITY earth		"&#x2641;">		<!-- Earth symbol -->
<!ENTITY moon		"&#x263E;">		<!-- Moon symbol -->
<!ENTITY mars		"&#x2642;">		<!-- Mars symbol -->
<!ENTITY jupiter	"&#x2643;">		<!-- Jupiter symbol -->
<!ENTITY saturn		"&#x2644;">		<!-- Saturn symbol -->
<!ENTITY uranus		"&#x2645;">		<!-- Uranus symbol -->
<!ENTITY neptune	"&#x2646;">		<!-- Neptune symbol -->
<!ENTITY pluto		"&#x2647;">		<!-- Pluto symbol -->
<!ENTITY farcm		".&#x2032;">		<!-- Fractional arc minute (arcmin above dec point) -->
<!ENTITY farcs		".&#x2033;">		<!-- Fractional arc second (arcsec above dec point) -->
<!ENTITY fd		".&#x0369;">	<!-- Fractional day (d over dot) -->
<!ENTITY fh		".&#x036A;">	<!-- Fractional hour (h over dot) -->
<!ENTITY fm		".&#x036B;">	<!-- Fractional minute (m over dot) -->
<!ENTITY fs		".&#x02E2;">	<!-- Fractional second (s over dot) -->
<!ENTITY fdg		".&#x00B0;">	<!-- Fractional degrees (degree symbol over dot) -->
<!ENTITY fp		".&#x1D56;">	<!-- Fractional period (P over dot) -->
<!ENTITY j0		"&#x00B0;">		<!-- J dot (the dot of a j) -->

<!-- UCP entities -->
<!ENTITY rarrr          "&longrightarrow;">
<!ENTITY larrr          "&longleftarrow;">
<!ENTITY sbond          "&ndash;">
<!ENTITY dbond          "&equals;">
<!ENTITY tbond          "&equiv;">




